# COVID-19 dataset 

by http://ncov.bii.virginia.edu/dashboard/

In [5]:
# imports
import numpy as np
import pandas as pd

In [45]:
#load files


import os
from os.path import join, getsize
for root, dirs, files in os.walk('../Data/nssac-ncov-data-country-state'):
    #print(root, "consumes", end="")
    #print("\n")
    #print(sum([getsize(join(root, name)) for name in files]), end="")
    #print("bytes in", len(files), "non-directory files")
    #print([name for name in files if name.find('csv')])
    #print(type(files))
    #f_path='../Data/nssac-ncov-data-country-state/'+files[0]
    #day1 = pd.read_csv(f_path)
    #display(day1[day1.Region == 'USA'])
    
    for name in files:
        if name.endswith('.csv'):
            print(name)
            f_path='../Data/nssac-ncov-data-country-state/'+name
            day = pd.read_csv(f_path)
            display(day[day.Region == 'USA'])

nssac-ncov-sd-01-22-2020.csv

          name Region          Last Update  Confirmed  Deaths  Recovered
27  Washington    USA  2020-01-22 12:00:00          1       0          0

nssac-ncov-sd-01-23-2020.csv

          name Region          Last Update  Confirmed  Deaths  Recovered
36  Washington    USA  2020-01-23 12:00:00          1       0          0

nssac-ncov-sd-01-24-2020.csv

          name Region          Last Update  Confirmed  Deaths  Recovered
36    Illinois    USA  2020-01-24 12:00:00          1       0          0
39  Washington    USA  2020-01-24 12:00:00          1       0          0

nssac-ncov-sd-01-25-2020.csv

          name Region          Last Update  Confirmed  Deaths  Recovered
40    Illinois    USA  2020-01-25 12:00:00          1       0          0
43  Washington    USA  2020-01-25 12:00:00          1       0          0

nssac-ncov-sd-01-26-2020.csv

          name Region          Last Update  Confirmed  Deaths  Recovered
40  California    USA  2020-01-26 23:00:00          2       0          0
42     Arizona    USA  2020-01-26 23:00:00          1       0          0
44    Illinois    USA  2020-01-26 23:00:00          1       0          0
46  Washington    USA  2020-01-26 23:00:00          1       0          0

nssac-ncov-sd-01-27-2020.csv

          name Region          Last Update  Confirmed  Deaths  Recovered
40  California    USA  2020-01-27 20:30:00          2       0          0
42     Arizona    USA  2020-01-27 20:30:00          1       0          0
46    Illinois    USA  2020-01-27 20:30:00          1       0          0
49  Washington    USA  2020-01-27 20:30:00          1       0          0

nssac-ncov-sd-01-28-2020.csv

          name Region          Last Update  Confirmed  Deaths  Recovered
41  California    USA  2020-01-28 23:00:00          2       0          0
44     Arizona    USA  2020-01-28 23:00:00          1       0          0
46    Illinois    USA  2020-01-28 23:00:00          1       0          0
49  Washington    USA  2020-01-28 18:00:00          1       0          0

nssac-ncov-sd-01-29-2020.csv

          name Region          Last Update  Confirmed  Deaths  Recovered
43  California    USA  2020-01-29 21:00:00          2       0          0
45     Arizona    USA  2020-01-29 21:00:00          1       0          0
48    Illinois    USA  2020-01-29 21:00:00          1       0          0
52  Washington    USA  2020-01-29 21:00:00          1       0          0

nssac-ncov-sd-01-30-2020.csv

          name Region          Last Update  Confirmed  Deaths  Recovered
43  California    USA  2020-01-30 21:30:00          2       0          0
44    Illinois    USA  2020-01-30 21:30:00          2       0          0
47     Arizona    USA  2020-01-30 21:30:00          1       0          0
55  Washington    USA  2020-01-30 21:30:00          1       0          0

nssac-ncov-sd-01-31-2020.csv

          name Region          Last Update  Confirmed  Deaths  Recovered
42  California    USA  2020-01-31 17:00:00          3       0          0
44    Illinois    USA  2020-01-31 14:00:00          2       0          0
49     Arizona    USA  2020-01-31 14:00:00          1       0          0
58  Washington    USA  2020-01-31 14:00:00          1       0          0

nssac-ncov-sd-02-01-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
44     California    USA  2020-02-01 19:53:00          3       0          0
45       Illinois    USA  2020-02-01 19:43:00          2       0          0
50        Arizona    USA  2020-02-01 19:43:00          1       0          0
54  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
60     Washington    USA  2020-02-01 19:43:00          1       0          0

nssac-ncov-sd-02-02-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
44     California    USA  2020-02-02 19:53:00          4       0          0
45       Illinois    USA  2020-02-01 19:43:00          2       0          0
51        Arizona    USA  2020-02-01 19:43:00          1       0          0
54  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
60     Washington    USA  2020-02-01 19:43:00          1       0          0

nssac-ncov-sd-02-03-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
45     California    USA  2020-02-03 03:53:00          6       0          0
46       Illinois    USA  2020-02-01 19:43:00          2       0          0
51        Arizona    USA  2020-02-01 19:43:00          1       0          0
54  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
60     Washington    USA  2020-02-01 19:43:00          1       0          0

nssac-ncov-sd-02-04-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
45     California    USA  2020-02-03 03:53:00          6       0          0
46       Illinois    USA  2020-02-01 19:43:00          2       0          0
51        Arizona    USA  2020-02-01 19:43:00          1       0          0
55  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
61     Washington    USA  2020-02-01 19:43:00          1       0          0

nssac-ncov-sd-02-05-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
45     California    USA  2020-02-03 03:53:00          6       0          0
46       Illinois    USA  2020-02-01 19:43:00          2       0          0
51        Arizona    USA  2020-02-01 19:43:00          1       0          0
55  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
61     Washington    USA  2020-02-01 19:43:00          1       0          0

nssac-ncov-sd-02-06-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
45     California    USA  2020-02-03 03:53:00          6       0          0
46       Illinois    USA  2020-02-01 19:43:00          2       0          0
51        Arizona    USA  2020-02-01 19:43:00          1       0          0
55  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
61     Washington    USA  2020-02-01 19:43:00          1       0          0
62      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-07-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
49     California    USA  2020-02-03 03:53:00          6       0          0
50       Illinois    USA  2020-02-01 19:43:00          2       0          0
52        Arizona    USA  2020-02-01 19:43:00          1       0          0
56  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
62     Washington    USA  2020-02-01 19:43:00          1       0          0
63      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-08-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
49     California    USA  2020-02-03 03:53:00          6       0          0
50       Illinois    USA  2020-02-01 19:43:00          2       0          0
52        Arizona    USA  2020-02-01 19:43:00          1       0          0
56  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
62     Washington    USA  2020-02-01 19:43:00          1       0          0
63      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-09-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
49     California    USA  2020-02-03 03:53:00          6       0          0
50       Illinois    USA  2020-02-03 03:43:00          2       0          0
52        Arizona    USA  2020-02-01 19:43:00          1       0          0
56  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
62     Washington    USA  2020-02-09 07:03:00          1       0          1
63      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-10-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
58     California    USA  2020-02-03 03:53:00          6       0          1
59       Illinois    USA  2020-02-03 03:43:00          2       0          0
60        Arizona    USA  2020-02-01 19:43:00          1       0          0
61  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
62     Washington    USA  2020-02-09 07:03:00          1       0          1
63      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-11-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
58     California    USA  2020-02-11 01:23:05          7       0          1
59       Illinois    USA  2020-02-09 19:03:03          2       0          2
60        Arizona    USA  2020-02-01 19:43:00          1       0          0
61  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
62     Washington    USA  2020-02-09 07:03:00          1       0          1
63      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-12-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
58     California    USA  2020-02-11 01:23:05          8       0          1
59       Illinois    USA  2020-02-09 19:03:03          2       0          2
60        Arizona    USA  2020-02-01 19:43:00          1       0          0
61  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
62     Washington    USA  2020-02-09 07:03:00          1       0          1
63      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-13-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
58     California    USA  2020-02-13 03:13:08          8       0          1
59       Illinois    USA  2020-02-09 19:03:03          2       0          2
60        Arizona    USA  2020-02-01 19:43:00          1       0          0
61  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
62     Washington    USA  2020-02-09 07:03:00          1       0          1
63      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-14-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
59     California    USA  2020-02-13 03:13:08          8       0          1
60       Illinois    USA  2020-02-09 19:03:03          2       0          2
61        Arizona    USA  2020-02-01 19:43:00          1       0          0
62  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
63     Washington    USA  2020-02-09 07:03:00          1       0          1
64      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-15-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
59     California    USA  2020-02-13 03:13:08          8       0          1
60       Illinois    USA  2020-02-09 19:03:03          2       0          2
61        Arizona    USA  2020-02-01 19:43:00          1       0          0
62  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
63     Washington    USA  2020-02-09 07:03:00          1       0          1
64      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-16-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
59     California    USA  2020-02-13 03:13:08          8       0          1
60       Illinois    USA  2020-02-09 19:03:03          2       0          2
61        Arizona    USA  2020-02-01 19:43:00          1       0          0
62  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
63     Washington    USA  2020-02-09 07:03:00          1       0          1
64      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-17-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
59     California    USA  2020-02-13 03:13:08          8       0          1
60       Illinois    USA  2020-02-09 19:03:03          2       0          2
61        Arizona    USA  2020-02-01 19:43:00          1       0          0
62  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
63     Washington    USA  2020-02-09 07:03:00          1       0          1
64      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-18-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
59     California    USA  2020-02-13 03:13:08          8       0          1
60       Illinois    USA  2020-02-09 19:03:03          2       0          2
61        Arizona    USA  2020-02-01 19:43:00          1       0          0
62  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
63     Washington    USA  2020-02-09 07:03:00          1       0          1
64      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-19-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
60     California    USA  2020-02-13 03:13:08          8       0          1
61       Illinois    USA  2020-02-09 19:03:03          2       0          2
62        Arizona    USA  2020-02-01 19:43:00          1       0          0
63  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
64     Washington    USA  2020-02-09 07:03:00          1       0          1
65      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-20-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
60     California    USA  2020-02-13 03:13:08          8       0          1
61       Illinois    USA  2020-02-09 19:03:03          2       0          2
62        Arizona    USA  2020-02-01 19:43:00          1       0          0
63  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
64     Washington    USA  2020-02-09 07:03:00          1       0          1
65      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-21-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
63     California    USA  2020-02-22 02:00:00         10       0          2
64       Illinois    USA  2020-02-09 19:03:03          2       0          2
65        Arizona    USA  2020-02-01 19:43:00          1       0          0
66  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
67     Washington    USA  2020-02-09 07:03:00          1       0          1
68      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-22-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
63     California    USA  2020-02-22 03:00:00         10       0          2
64       Illinois    USA  2020-02-09 19:03:03          2       0          2
65        Arizona    USA  2020-02-01 19:43:00          1       0          0
66  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
67     Washington    USA  2020-02-09 07:03:00          1       0          1
68      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-23-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
63     California    USA  2020-02-22 03:00:00         10       0          2
64       Illinois    USA  2020-02-09 19:03:03          2       0          2
65        Arizona    USA  2020-02-01 19:43:00          1       0          0
66  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
67     Washington    USA  2020-02-09 07:03:00          1       0          1
68      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-24-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
67     California    USA  2020-02-22 03:00:00         10       0          2
68       Illinois    USA  2020-02-09 19:03:03          2       0          2
69        Arizona    USA  2020-02-01 19:43:00          1       0          0
70  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
71     Washington    USA  2020-02-09 07:03:00          1       0          1
72      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-25-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
72     California    USA  2020-02-22 03:00:00         10       0          2
73       Illinois    USA  2020-02-09 19:03:03          2       0          2
74        Arizona    USA  2020-02-25 21:00:00          1       0          1
75  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
76     Washington    USA  2020-02-09 07:03:00          1       0          1
77      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-26-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
79     California    USA  2020-02-26 20:00:00         11       0          2
80       Illinois    USA  2020-02-09 19:03:03          2       0          2
81        Arizona    USA  2020-02-25 21:00:00          1       0          1
82  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
83     Washington    USA  2020-02-09 07:03:00          1       0          1
84      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-27-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
84     California    USA  2020-02-26 20:00:00         11       0          2
85       Illinois    USA  2020-02-09 19:03:03          2       0          2
86        Arizona    USA  2020-02-25 21:00:00          1       0          1
87  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
88     Washington    USA  2020-02-09 07:03:00          1       0          1
89      Wisconsin    USA  2020-02-05 21:53:00          1       0          0

nssac-ncov-sd-02-28-2020.csv

             name Region          Last Update  Confirmed  Deaths  Recovered
91     California    USA  2020-02-29 01:00:00         12       0          2
92       Illinois    USA  2020-02-09 19:03:03          2       0          2
93        Arizona    USA  2020-02-25 21:00:00          1       0          1
94  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
95     Washington    USA  2020-02-29 04:00:00          3       0          1
96      Wisconsin    USA  2020-02-05 21:53:00          1       0          0
97         Oregon    USA  2020-02-29 02:30:00          1       0          0

nssac-ncov-sd-02-29-2020.csv

              name Region          Last Update  Confirmed  Deaths  Recovered
95      California    USA  2020-03-01 03:00:00         13       0          2
96        Illinois    USA  2020-03-01 04:00:00          3       0          2
97         Arizona    USA  2020-02-25 21:00:00          1       0          1
98   Massachusetts    USA  2020-02-01 19:43:00          1       0          0
99      Washington    USA  2020-02-29 19:00:00          5       1          1
100      Wisconsin    USA  2020-02-05 21:53:00          1       0          0
101         Oregon    USA  2020-02-29 02:30:00          1       0          0

nssac-ncov-sd-03-01-2020.csv

              name Region          Last Update  Confirmed  Deaths  Recovered
98      California    USA  2020-03-02 03:00:00         16       0          2
99      Washington    USA  2020-03-02 03:00:00         12       2          1
100       Illinois    USA  2020-03-01 04:00:00          3       0          2
101        Arizona    USA  2020-02-25 21:00:00          1       0          1
102  Massachusetts    USA  2020-02-01 19:43:00          1       0          0
103      Wisconsin    USA  2020-02-05 21:53:00          1       0          0
104         Oregon    USA  2020-03-02 03:00:00          2       0          0
105   Rhode Island    USA  2020-03-01 19:00:00          1       0          0
106       New York    USA  2020-03-02 03:00:00          1       0          0
107        Florida    USA  2020-03-02 03:00:00          2       0          0

nssac-ncov-sd-03-02-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
106,Unknown location US,USA,2020-03-02 17:00:00,48,0,0
107,California,USA,2020-03-02 03:00:00,19,0,2
108,Washington,USA,2020-03-02 19:50:00,18,6,1
109,Illinois,USA,2020-03-02 18:30:00,4,0,2
110,Arizona,USA,2020-02-25 21:00:00,1,0,1
111,Massachusetts,USA,2020-03-03 03:00:00,2,0,0
112,Wisconsin,USA,2020-02-05 21:53:00,1,0,0
113,Oregon,USA,2020-03-02 18:30:00,3,0,0
114,Rhode Island,USA,2020-03-02 22:00:00,2,0,0
115,New York,USA,2020-03-02 03:00:00,1,0,0
116,Florida,USA,2020-03-02 03:00:00,2,0,0
117,New Hampshire,USA,2020-03-02 17:00:00,1,0,0
118,Georgia,USA,2020-03-03 03:00:00,2,0,0

nssac-ncov-sd-03-03-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
110,Unknown location US,USA,2020-03-02 17:00:00,48,0,0
111,California,USA,2020-03-03 22:00:00,26,0,2
112,Washington,USA,2020-03-03 20:00:00,27,9,1
113,Illinois,USA,2020-03-02 18:30:00,4,0,2
114,Arizona,USA,2020-03-03 22:00:00,2,0,1
115,Massachusetts,USA,2020-03-03 03:00:00,2,0,0
116,Wisconsin,USA,2020-02-05 21:53:00,1,0,0
117,Oregon,USA,2020-03-02 18:30:00,3,0,0
118,Rhode Island,USA,2020-03-02 22:00:00,2,0,0
119,New York,USA,2020-03-03 19:00:00,2,0,0
120,Florida,USA,2020-03-03 17:52:00,3,0,0
121,New Hampshire,USA,2020-03-04 03:00:00,2,0,0
122,Georgia,USA,2020-03-03 03:00:00,2,0,0
123,North Carolina,USA,2020-03-03 21:00:00,1,0,0

nssac-ncov-sd-03-04-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
113,Unknown location US,USA,2020-03-02 17:00:00,48,0,0
114,California,USA,2020-03-05 00:00:00,36,1,2
115,Washington,USA,2020-03-04 19:30:00,39,10,1
116,Illinois,USA,2020-03-02 18:30:00,4,0,2
117,Texas,USA,2020-03-05 00:00:00,1,0,0
118,Arizona,USA,2020-03-03 22:00:00,2,0,1
119,Massachusetts,USA,2020-03-03 03:00:00,2,0,0
120,Wisconsin,USA,2020-02-05 21:53:00,1,0,0
121,Oregon,USA,2020-03-02 18:30:00,3,0,0
122,Rhode Island,USA,2020-03-02 22:00:00,2,0,0
123,New York,USA,2020-03-04 21:00:00,11,0,0
124,Florida,USA,2020-03-03 17:52:00,3,0,0
125,New Hampshire,USA,2020-03-04 03:00:00,2,0,0
126,Georgia,USA,2020-03-03 03:00:00,2,0,0
127,North Carolina,USA,2020-03-03 21:00:00,1,0,0
128,New Jersey,USA,2020-03-05 02:00:00,1,0,0

nssac-ncov-sd-03-05-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
120,Unknown location US,USA,2020-03-02 17:00:00,48,0,0
121,California,USA,2020-03-05 23:30:00,49,1,2
122,Washington,USA,2020-03-05 20:00:00,75,11,1
123,Illinois,USA,2020-03-05 19:00:00,5,0,2
124,Texas,USA,2020-03-05 21:45:00,3,0,0
125,Arizona,USA,2020-03-03 22:00:00,2,0,1
126,Massachusetts,USA,2020-03-06 03:00:00,4,0,0
127,Wisconsin,USA,2020-02-05 21:53:00,1,0,0
128,Oregon,USA,2020-03-02 18:30:00,3,0,0
129,Rhode Island,USA,2020-03-02 22:00:00,2,0,0
130,New York,USA,2020-03-05 19:00:00,22,0,0
131,Florida,USA,2020-03-05 17:00:00,4,0,0
132,New Hampshire,USA,2020-03-04 03:00:00,2,0,0
133,Georgia,USA,2020-03-03 03:00:00,2,0,0
134,North Carolina,USA,2020-03-03 21:00:00,1,0,0
135,New Jersey,USA,2020-03-05 21:45:00,2,0,0
136,Tennessee,USA,2020-03-05 15:00:00,1,0,0
137,Nevada,USA,2020-03-05 17:00:00,1,0,0
138,Colorado,USA,2020-03-06 03:00:00,2,0,0
139,Maryland,USA,2020-03-05 23:30:00,3,0,0

nssac-ncov-sd-03-06-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
130,Diamond Princess,USA,2020-03-02 17:00:00,45,0,0
131,Wuhan Evacuee,USA,2020-03-02 17:00:00,3,0,0
133,Washington,USA,2020-03-07 03:00:00,86,14,1
134,California,USA,2020-03-07 03:00:00,66,1,2
135,New York,USA,2020-03-07 01:00:00,44,0,0
136,Massachusetts,USA,2020-03-06 20:00:00,8,0,0
137,Illinois,USA,2020-03-07 03:00:00,6,0,2
138,Texas,USA,2020-03-07 03:00:00,9,0,0
139,Florida,USA,2020-03-07 03:00:00,7,2,0
140,New Jersey,USA,2020-03-07 01:00:00,4,0,0
141,Arizona,USA,2020-03-06 18:00:00,3,0,1
142,Wisconsin,USA,2020-02-05 21:53:00,1,0,0
143,Oregon,USA,2020-03-02 18:30:00,3,0,0
144,Rhode Island,USA,2020-03-07 03:00:00,3,0,0
145,New Hampshire,USA,2020-03-04 03:00:00,2,0,0
146,Georgia,USA,2020-03-06 18:00:00,3,0,0
147,North Carolina,USA,2020-03-06 16:00:00,2,0,0
148,Tennessee,USA,2020-03-05 15:00:00,1,0,0
149,Nevada,USA,2020-03-06 20:00:00,2,0,0
150,Colorado,USA,2020-03-07 01:00:00,8,0,0
151,Maryland,USA,2020-03-07 01:00:00,3,0,0
152,Pennsylvania,USA,2020-03-06 16:00:00,2,0,0
153,Indiana,USA,2020-03-06 16:40:00,1,0,0
154,Minnesota,USA,2020-03-07 01:00:00,1,0,0
155,Kentucky,USA,2020-03-07 01:00:00,1,0,0
156,Oklahoma,USA,2020-03-07 01:00:00,1,0,0
157,Connecticut,USA,2020-03-07 01:00:00,1,0,0
158,South Carolina,USA,2020-03-07 03:00:00,2,0,0
159,Hawaii,USA,2020-03-07 03:00:00,1,0,0
160,Utah,USA,2020-03-07 03:00:00,1,0,0
161,Nebraska,USA,2020-03-07 03:00:00,1,0,0

nssac-ncov-sd-03-07-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
134,Diamond Princess,USA,2020-03-02 17:00:00,45,0,0
135,Wuhan Evacuee,USA,2020-03-02 17:00:00,3,0,0
137,Washington,USA,2020-03-07 03:00:00,108,16,1
138,California,USA,2020-03-07 23:00:00,84,1,2
139,New York,USA,2020-03-08 01:00:00,89,0,0
140,Massachusetts,USA,2020-03-08 01:00:00,14,0,1
141,Illinois,USA,2020-03-07 03:00:00,6,0,2
142,Texas,USA,2020-03-07 03:00:00,9,0,0
143,Florida,USA,2020-03-08 01:00:00,11,2,0
144,New Jersey,USA,2020-03-07 01:00:00,4,0,0
145,Arizona,USA,2020-03-07 18:30:00,5,0,1
146,Wisconsin,USA,2020-02-05 21:53:00,1,0,1
147,Oregon,USA,2020-03-07 20:00:00,7,0,0
148,Rhode Island,USA,2020-03-07 03:00:00,3,0,0
149,New Hampshire,USA,2020-03-04 03:00:00,2,0,0
150,Georgia,USA,2020-03-07 16:30:00,5,0,0
151,North Carolina,USA,2020-03-06 16:00:00,2,0,0
152,Tennessee,USA,2020-03-05 15:00:00,1,0,0
153,Nevada,USA,2020-03-06 20:00:00,2,0,0
154,Colorado,USA,2020-03-07 01:00:00,8,0,0
155,Maryland,USA,2020-03-07 01:00:00,3,0,0
156,Pennsylvania,USA,2020-03-07 01:00:00,4,0,0
157,Indiana,USA,2020-03-06 16:40:00,1,0,0
158,Minnesota,USA,2020-03-07 01:00:00,1,0,0
159,Kentucky,USA,2020-03-07 01:00:00,1,0,0
160,Oklahoma,USA,2020-03-07 01:00:00,1,0,0
161,Connecticut,USA,2020-03-07 20:00:00,2,0,0
162,South Carolina,USA,2020-03-07 03:00:00,2,0,0
163,Hawaii,USA,2020-03-07 03:00:00,1,0,0
164,Utah,USA,2020-03-07 03:00:00,1,0,0
165,Nebraska,USA,2020-03-07 03:00:00,1,0,0
166,District of Columbia,USA,2020-03-07 03:00:00,1,0,0
167,Kansas,USA,2020-03-08 01:00:00,1,0,0
168,Virginia,USA,2020-03-08 01:00:00,1,0,0
169,Missouri,USA,2020-03-08 02:30:00,1,0,0

nssac-ncov-sd-03-08-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
137,Diamond Princess,USA,2020-03-02 17:00:00,45,0,0
138,Wuhan Evacuee,USA,2020-03-02 17:00:00,3,0,0
139,Grand Princess,USA,2020-03-07 01:00:00,21,0,0
140,Washington,USA,2020-03-08 22:00:00,136,19,1
141,California,USA,2020-03-08 23:30:00,99,1,2
142,New York,USA,2020-03-08 23:30:00,105,0,0
143,Massachusetts,USA,2020-03-08 21:00:00,28,0,1
144,Illinois,USA,2020-03-08 21:00:00,7,0,2
145,Texas,USA,2020-03-08 16:00:00,12,0,0
146,Florida,USA,2020-03-08 23:30:00,13,2,0
147,New Jersey,USA,2020-03-08 21:00:00,6,0,0
148,Arizona,USA,2020-03-07 18:30:00,5,0,1
149,Wisconsin,USA,2020-02-05 21:53:00,1,0,1
150,Oregon,USA,2020-03-08 21:00:00,14,0,0
151,Rhode Island,USA,2020-03-07 03:00:00,3,0,0
152,New Hampshire,USA,2020-03-07 12:00:00,4,0,0
153,Georgia,USA,2020-03-08 13:00:00,7,0,0
154,North Carolina,USA,2020-03-06 16:00:00,2,0,0
155,Tennessee,USA,2020-03-08 23:30:00,3,0,0
156,Nevada,USA,2020-03-08 22:30:00,4,0,0
157,Colorado,USA,2020-03-07 01:00:00,8,0,0
158,Maryland,USA,2020-03-09 02:00:00,5,0,0
159,Pennsylvania,USA,2020-03-08 22:00:00,6,0,0
160,Indiana,USA,2020-03-08 21:00:00,2,0,0
161,Minnesota,USA,2020-03-09 01:00:00,2,0,0
162,Kentucky,USA,2020-03-08 23:30:00,4,0,0
163,Oklahoma,USA,2020-03-07 01:00:00,1,0,0
164,Connecticut,USA,2020-03-07 20:00:00,1,0,0
165,South Carolina,USA,2020-03-08 22:00:00,6,0,0
166,Hawaii,USA,2020-03-07 03:00:00,1,0,0
167,Utah,USA,2020-03-07 03:00:00,1,0,0
168,Nebraska,USA,2020-03-09 01:00:00,3,0,0
169,District of Columbia,USA,2020-03-08 14:00:00,2,0,0
170,Kansas,USA,2020-03-08 01:00:00,1,0,0
171,Virginia,USA,2020-03-08 14:00:00,2,0,0
172,Missouri,USA,2020-03-08 02:30:00,1,0,0
173,Vermont,USA,2020-03-08 13:00:00,1,0,0
174,Iowa,USA,2020-03-09 01:00:00,3,0,0

nssac-ncov-sd-03-09-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
142,Diamond Princess,USA,2020-03-02 17:00:00,46,0,0
143,Wuhan Evacuee,USA,2020-03-02 17:00:00,3,0,0
144,Grand Princess,USA,2020-03-07 01:00:00,21,0,0
145,Washington,USA,2020-03-10 02:00:00,167,22,1
146,New York,USA,2020-03-10 02:00:00,143,0,0
147,California,USA,2020-03-10 03:45:00,143,2,2
148,Massachusetts,USA,2020-03-10 02:00:00,41,0,1
149,Georgia,USA,2020-03-10 03:45:00,17,0,0
150,Oregon,USA,2020-03-08 21:00:00,14,0,0
151,Florida,USA,2020-03-10 02:00:00,14,2,0
152,Texas,USA,2020-03-10 03:45:00,13,0,0
153,Colorado,USA,2020-03-10 02:00:00,12,0,0
154,Illinois,USA,2020-03-10 02:00:00,11,0,2
155,New Jersey,USA,2020-03-09 19:00:00,11,0,0
156,Pennsylvania,USA,2020-03-10 02:00:00,10,0,0
157,Iowa,USA,2020-03-10 02:00:00,8,0,0
158,North Carolina,USA,2020-03-10 02:00:00,7,0,0
159,South Carolina,USA,2020-03-10 02:00:00,7,0,0
160,Virginia,USA,2020-03-10 03:45:00,7,0,0
161,Arizona,USA,2020-03-07 18:30:00,6,0,1
162,Maryland,USA,2020-03-10 02:00:00,6,0,0
163,Kentucky,USA,2020-03-10 02:00:00,6,0,0
164,Indiana,USA,2020-03-10 03:45:00,5,0,0
165,District of Columbia,USA,2020-03-10 03:45:00,5,0,0
166,New Hampshire,USA,2020-03-07 12:00:00,4,0,0
167,Nevada,USA,2020-03-08 22:30:00,4,0,0
168,Tennessee,USA,2020-03-08 23:30:00,4,0,0
169,Rhode Island,USA,2020-03-07 03:00:00,3,0,0
170,Nebraska,USA,2020-03-09 01:00:00,3,0,0
171,Ohio,USA,2020-03-09 19:00:00,3,0,0
172,Minnesota,USA,2020-03-09 01:00:00,2,0,0
173,Hawaii,USA,2020-03-09 11:30:00,2,0,0
174,Connecticut,USA,2020-03-10 02:00:00,2,0,0
175,Wisconsin,USA,2020-02-05 21:53:00,2,0,1
176,Oklahoma,USA,2020-03-07 01:00:00,1,0,0
177,Utah,USA,2020-03-07 03:00:00,1,0,0
178,Kansas,USA,2020-03-08 01:00:00,1,0,0
179,Missouri,USA,2020-03-08 02:30:00,1,0,0
180,Vermont,USA,2020-03-08 13:00:00,1,0,0
181,Louisiana,USA,2020-03-09 18:30:00,1,0,0

nssac-ncov-sd-03-10-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
145,Diamond Princess,USA,2020-03-02 17:00:00,46,0,0
146,Wuhan Evacuee,USA,2020-03-02 17:00:00,3,0,0
147,Grand Princess,USA,2020-03-07 01:00:00,21,0,0
148,Washington,USA,2020-03-10 23:00:00,272,24,1
149,New York,USA,2020-03-10 23:00:00,173,0,0
150,California,USA,2020-03-10 23:00:00,157,2,2
151,Massachusetts,USA,2020-03-10 23:00:00,92,0,1
152,Illinois,USA,2020-03-10 23:00:00,19,0,2
153,Georgia,USA,2020-03-10 03:45:00,17,0,0
154,Texas,USA,2020-03-10 23:00:00,17,0,0
155,Oregon,USA,2020-03-10 23:00:00,15,0,0
156,Florida,USA,2020-03-10 14:00:00,15,2,0
157,New Jersey,USA,2020-03-10 18:00:00,15,1,0
158,Colorado,USA,2020-03-10 18:00:00,15,0,0
159,Iowa,USA,2020-03-10 23:30:00,13,0,0
160,Pennsylvania,USA,2020-03-10 18:00:00,12,0,0
161,Maryland,USA,2020-03-10 23:00:00,9,0,0
162,South Carolina,USA,2020-03-10 23:00:00,9,0,0
163,Kentucky,USA,2020-03-10 23:00:00,8,0,0
164,Virginia,USA,2020-03-10 18:00:00,8,0,0
165,North Carolina,USA,2020-03-10 02:00:00,7,0,0
166,Tennessee,USA,2020-03-10 23:00:00,7,0,0
167,Arizona,USA,2020-03-07 18:30:00,6,0,1
168,Indiana,USA,2020-03-10 15:40:00,6,0,0
169,South Dakota,USA,2020-03-10 23:00:00,5,1,0
170,Rhode Island,USA,2020-03-10 23:00:00,5,0,0
171,New Hampshire,USA,2020-03-10 23:00:00,5,0,0
172,District of Columbia,USA,2020-03-10 03:45:00,5,0,0
173,Nevada,USA,2020-03-08 22:30:00,4,0,0
174,Wisconsin,USA,2020-02-10 17:00:00,3,0,1
175,Minnesota,USA,2020-03-10 23:00:00,3,0,0
176,Nebraska,USA,2020-03-09 01:00:00,3,0,0
177,Louisiana,USA,2020-03-10 23:30:00,3,0,0
178,Ohio,USA,2020-03-09 19:00:00,3,0,0
179,Oklahoma,USA,2020-03-10 17:00:00,2,0,0
180,Hawaii,USA,2020-03-09 11:30:00,2,0,0
181,Utah,USA,2020-03-10 14:30:00,2,0,0
182,Michigan,USA,2020-03-11 03:00:00,2,0,0
183,Connecticut,USA,2020-03-10 02:00:00,2,0,0
184,Kansas,USA,2020-03-08 01:00:00,1,0,0
185,Missouri,USA,2020-03-08 02:30:00,1,0,0
186,Vermont,USA,2020-03-08 13:00:00,1,0,0

nssac-ncov-sd-03-11-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
146,Diamond Princess,USA,2020-03-02 17:00:00,46,0,0
147,Wuhan Evacuee,USA,2020-03-02 17:00:00,3,0,0
148,Grand Princess,USA,2020-03-07 01:00:00,21,0,0
149,Washington,USA,2020-03-12 02:00:00,373,30,1
150,New York,USA,2020-03-11 21:00:00,218,0,0
151,California,USA,2020-03-12 02:00:00,177,4,2
152,Massachusetts,USA,2020-03-11 02:00:00,95,0,1
153,Colorado,USA,2020-03-12 02:00:00,34,0,0
154,Georgia,USA,2020-03-12 03:00:00,31,0,0
155,Florida,USA,2020-03-12 02:00:00,29,2,0
156,Illinois,USA,2020-03-11 21:00:00,25,0,2
157,New Jersey,USA,2020-03-11 19:20:00,23,1,0
158,Texas,USA,2020-03-12 02:00:00,22,0,0
159,Oregon,USA,2020-03-11 21:00:00,19,0,0
160,Pennsylvania,USA,2020-03-11 21:00:00,16,0,0
161,Iowa,USA,2020-03-12 02:00:00,14,0,0
162,Louisiana,USA,2020-03-12 02:00:00,13,0,0
163,Maryland,USA,2020-03-12 02:00:00,12,0,0
164,Indiana,USA,2020-03-12 02:00:00,11,0,0
165,South Carolina,USA,2020-03-12 02:00:00,10,0,0
166,District of Columbia,USA,2020-03-12 02:00:00,10,0,0
167,Arizona,USA,2020-03-11 18:00:00,9,0,1
168,North Carolina,USA,2020-03-12 02:00:00,9,0,0
169,Tennessee,USA,2020-03-12 02:00:00,9,0,0
170,Virginia,USA,2020-03-11 15:50:00,9,0,0
171,Kentucky,USA,2020-03-10 23:00:00,8,0,0
172,South Dakota,USA,2020-03-12 02:00:00,8,1,0
173,Nevada,USA,2020-03-12 02:00:00,7,0,0
174,Wisconsin,USA,2020-02-12 02:00:00,6,0,1
175,Rhode Island,USA,2020-03-10 23:00:00,5,0,0
176,New Hampshire,USA,2020-03-10 23:00:00,5,0,0
177,Minnesota,USA,2020-03-11 19:00:00,5,0,0
178,Nebraska,USA,2020-03-11 14:00:00,5,0,0
179,Ohio,USA,2020-03-11 19:00:00,4,0,0
180,New Mexico,USA,2020-03-11 16:20:00,3,0,0
181,Others (repatriated from Wuhan),USA,2020-03-11 02:00:00,3,0,0
182,Utah,USA,2020-03-12 02:00:00,3,0,0
183,Connecticut,USA,2020-03-12 02:00:00,3,0,0
184,Oklahoma,USA,2020-03-10 17:00:00,2,0,0
185,Hawaii,USA,2020-03-09 11:30:00,2,0,0
186,Vermont,USA,2020-03-12 02:00:00,2,0,0
187,Michigan,USA,2020-03-11 03:00:00,2,0,0
188,Kansas,USA,2020-03-08 01:00:00,1,0,0
189,Missouri,USA,2020-03-08 02:30:00,1,0,0
190,Arkansas,USA,2020-03-11 18:00:00,1,0,0
191,Montana,USA,2020-03-11 18:00:00,1,0,0
192,Delaware,USA,2020-03-11 21:00:00,1,0,0
193,Mississippi,USA,2020-03-12 02:00:00,1,0,0
194,Wyoming,USA,2020-03-12 02:00:00,1,0,0
195,North Dakota,USA,2020-03-12 02:00:00,1,0,0

nssac-ncov-sd-03-12-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
148,Diamond Princess,USA,2020-03-02 17:00:00,46,0,0
149,Wuhan Evacuee,USA,2020-03-02 17:00:00,3,0,0
150,Grand Princess,USA,2020-03-07 01:00:00,21,0,0
151,Washington,USA,2020-03-13 02:00:00,457,31,1
152,New York,USA,2020-03-12 23:00:00,325,0,0
153,California,USA,2020-03-13 02:00:00,243,4,2
154,Massachusetts,USA,2020-03-12 20:00:00,108,0,1
155,Florida,USA,2020-03-13 03:00:00,50,2,0
156,Colorado,USA,2020-03-13 02:00:00,50,0,0
157,Georgia,USA,2020-03-13 03:00:00,38,1,0
158,Illinois,USA,2020-03-12 23:00:00,32,0,2
159,Texas,USA,2020-03-13 03:00:00,32,0,0
160,New Jersey,USA,2020-03-13 02:00:00,31,1,0
161,Oregon,USA,2020-03-13 03:00:00,30,0,0
162,Pennsylvania,USA,2020-03-12 14:00:00,22,0,0
163,Louisiana,USA,2020-03-13 02:00:00,19,0,0
164,Tennessee,USA,2020-03-13 02:00:00,18,0,0
165,Virginia,USA,2020-03-13 02:00:00,18,0,0
166,North Carolina,USA,2020-03-13 02:00:00,17,0,0
167,Iowa,USA,2020-03-13 02:00:00,16,0,0
168,Indiana,USA,2020-03-13 02:00:00,13,0,0
169,Maryland,USA,2020-03-12 02:00:00,12,0,0
170,South Carolina,USA,2020-03-13 02:00:00,12,0,0
171,Michigan,USA,2020-03-13 02:00:00,12,0,0
172,Nevada,USA,2020-03-13 02:00:00,11,0,0
173,Kentucky,USA,2020-03-13 02:00:00,11,0,0
174,Nebraska,USA,2020-03-13 03:00:00,11,0,0
175,District of Columbia,USA,2020-03-12 02:00:00,10,0,0
176,Arizona,USA,2020-03-11 18:00:00,9,0,1
177,Minnesota,USA,2020-03-13 02:00:00,9,0,0
178,Wisconsin,USA,2020-02-13 02:00:00,8,0,1
179,South Dakota,USA,2020-03-12 02:00:00,8,1,0
180,New Hampshire,USA,2020-03-13 02:00:00,6,0,0
181,Arkansas,USA,2020-03-13 02:00:00,6,0,0
182,New Mexico,USA,2020-03-13 03:00:00,6,0,0
183,Rhode Island,USA,2020-03-10 23:00:00,5,0,0
184,Utah,USA,2020-03-13 02:00:00,5,0,0
185,Kansas,USA,2020-03-13 02:00:00,5,1,0
186,Connecticut,USA,2020-03-13 02:00:00,5,0,0
187,Ohio,USA,2020-03-12 14:00:00,5,0,0
188,Delaware,USA,2020-03-12 17:00:00,4,0,0
189,Others (repatriated from Wuhan),USA,2020-03-11 02:00:00,3,0,0
190,Oklahoma,USA,2020-03-13 02:00:00,3,0,0
191,Hawaii,USA,2020-03-09 11:30:00,2,0,0
192,Missouri,USA,2020-03-13 02:00:00,2,0,0
193,Vermont,USA,2020-03-12 02:00:00,2,0,0
194,Mississippi,USA,2020-03-12 02:00:00,1,0,0
195,Wyoming,USA,2020-03-12 02:00:00,1,0,0
196,North Dakota,USA,2020-03-12 02:00:00,1,0,0
197,Montana,USA,2020-03-11 18:00:00,1,0,0
198,Maine,USA,2020-03-12 17:20:00,1,0,0
199,Alaska,USA,2020-03-13 02:00:00,1,0,0

nssac-ncov-sd-03-13-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
169,Diamond Princess,USA,2020-03-02 17:00:00,46,0,0
170,Wuhan Evacuee,USA,2020-03-02 17:00:00,3,0,0
171,Grand Princess,USA,2020-03-07 01:00:00,21,0,0
172,Washington,USA,2020-03-14 02:00:00,568,37,1
173,New York,USA,2020-03-13 20:00:00,421,0,0
174,California,USA,2020-03-14 02:00:00,295,5,2
175,Massachusetts,USA,2020-03-14 02:00:00,123,0,1
176,Colorado,USA,2020-03-14 02:00:00,77,1,0
177,Florida,USA,2020-03-13 03:00:00,51,3,0
178,New Jersey,USA,2020-03-14 02:00:00,50,1,0
179,Texas,USA,2020-03-14 14:00:00,49,0,0
180,Illinois,USA,2020-03-14 02:00:00,46,0,2
181,Georgia,USA,2020-03-14 02:00:00,42,1,0
182,Pennsylvania,USA,2020-03-14 02:00:00,41,0,0
183,Louisiana,USA,2020-03-14 02:00:00,36,0,0
184,Oregon,USA,2020-03-14 02:30:00,32,0,0
185,Virginia,USA,2020-03-13 20:00:00,30,0,0
186,Tennessee,USA,2020-03-14 02:00:00,26,0,0
187,Michigan,USA,2020-03-14 02:00:00,25,0,0
188,Nevada,USA,2020-03-14 02:00:00,20,0,0
189,Wisconsin,USA,2020-02-14 02:00:00,19,0,1
190,North Carolina,USA,2020-03-14 03:00:00,19,0,0
191,Maryland,USA,2020-03-14 02:00:00,19,0,0
192,Iowa,USA,2020-03-14 02:00:00,17,0,0
193,Ohio,USA,2020-03-14 02:00:00,16,0,0
194,Rhode Island,USA,2020-03-14 02:00:00,14,0,0
195,Minnesota,USA,2020-03-14 02:00:00,14,0,0
196,Kentucky,USA,2020-03-14 02:00:00,14,0,0
197,Nebraska,USA,2020-03-14 02:00:00,14,0,0
198,Indiana,USA,2020-03-13 02:00:00,13,0,0
199,South Carolina,USA,2020-03-14 02:00:00,13,0,0
200,Connecticut,USA,2020-03-14 02:00:00,11,0,0
201,Arizona,USA,2020-03-14 02:00:00,10,0,1
202,District of Columbia,USA,2020-03-12 02:00:00,10,0,0
203,New Mexico,USA,2020-03-14 02:00:00,10,0,0
204,Utah,USA,2020-03-14 02:00:00,9,0,0
205,South Dakota,USA,2020-03-14 02:00:00,9,1,0
206,Arkansas,USA,2020-03-14 02:00:00,9,0,0
207,New Hampshire,USA,2020-03-13 02:00:00,6,0,0
208,Kansas,USA,2020-03-14 02:00:00,6,1,0
209,Mississippi,USA,2020-03-14 02:00:00,6,0,0
210,Montana,USA,2020-03-14 02:00:00,5,0,0
211,Alabama,USA,2020-03-14 02:00:00,6,0,0
212,Missouri,USA,2020-03-14 02:00:00,4,0,0
213,Delaware,USA,2020-03-12 17:00:00,4,0,0
214,Others (repatriated from Wuhan),USA,2020-03-11 02:00:00,3,0,0
215,Oklahoma,USA,2020-03-13 02:00:00,3,0,0
216,Maine,USA,2020-03-13 15:00:00,3,0,0
217,Hawaii,USA,2020-03-09 11:30:00,2,0,0
218,Vermont,USA,2020-03-12 02:00:00,2,0,0
219,Wyoming,USA,2020-03-12 02:00:00,1,0,0
220,North Dakota,USA,2020-03-12 02:00:00,1,0,0
221,Alaska,USA,2020-03-13 02:00:00,1,0,0
222,Idaho,USA,2020-03-14 02:00:00,1,0,0

nssac-ncov-sd-03-14-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
174,Washington,USA,2020-03-15 03:00:00,642,40,1
175,New York,USA,2020-03-15 03:00:00,615,2,0
176,California,USA,2020-03-15 03:00:00,374,5,2
177,Massachusetts,USA,2020-03-15 03:00:00,138,0,1
178,Florida,USA,2020-03-15 03:00:00,116,4,0
179,Colorado,USA,2020-03-15 03:00:00,101,1,0
180,Louisiana,USA,2020-03-15 03:00:00,77,1,0
181,Georgia,USA,2020-03-15 03:00:00,75,1,0
182,New Jersey,USA,2020-03-15 03:00:00,70,2,0
183,Illinois,USA,2020-03-15 03:00:00,66,0,2
184,Texas,USA,2020-03-15 03:00:00,63,0,0
185,Pennsylvania,USA,2020-03-15 03:00:00,47,0,0
186,Diamond Princess,USA,2020-03-15 03:00:00,46,0,0
187,Virginia,USA,2020-03-15 03:00:00,41,1,0
188,Oregon,USA,2020-03-15 03:00:00,36,1,0
189,Michigan,USA,2020-03-15 03:00:00,33,0,0
190,Tennessee,USA,2020-03-15 03:00:00,32,0,0
191,Maryland,USA,2020-03-15 03:00:00,28,0,0
192,Ohio,USA,2020-03-15 03:00:00,28,0,0
193,Wisconsin,USA,2020-03-15 03:00:00,27,0,1
194,North Carolina,USA,2020-03-15 03:00:00,26,0,0
195,Utah,USA,2020-03-15 03:00:00,24,0,0
196,Connecticut,USA,2020-03-15 03:00:00,23,0,0
197,Nevada,USA,2020-03-15 03:00:00,21,0,0
198,Minnesota,USA,2020-03-15 03:00:00,21,0,0
199,Rhode Island,USA,2020-03-15 03:00:00,20,0,0
200,Grand Princess,USA,2020-03-15 03:00:00,20,0,0
201,South Carolina,USA,2020-03-15 03:00:00,19,0,0
202,Iowa,USA,2020-03-15 03:00:00,18,0,0
203,Kentucky,USA,2020-03-15 03:00:00,18,0,0
204,Nebraska,USA,2020-03-15 03:00:00,17,0,0
205,District of Columbia,USA,2020-03-15 03:00:00,16,0,0
206,Indiana,USA,2020-03-15 03:00:00,16,0,0
207,New Mexico,USA,2020-03-15 03:00:00,13,0,0
208,Arizona,USA,2020-03-15 03:00:00,12,0,1
209,Arkansas,USA,2020-03-15 03:00:00,12,0,0
210,Alabama,USA,2020-03-15 03:00:00,12,0,0
211,South Dakota,USA,2020-03-15 03:00:00,9,1,0
212,Kansas,USA,2020-03-15 03:00:00,8,1,0
213,New Hampshire,USA,2020-03-15 03:00:00,7,0,0
214,Montana,USA,2020-03-15 03:00:00,7,0,0
215,Maine,USA,2020-03-15 03:00:00,6,0,0
216,Delaware,USA,2020-03-15 03:00:00,6,0,0
217,Hawaii,USA,2020-03-15 03:00:00,6,0,0
218,Mississippi,USA,2020-03-15 03:00:00,6,0,0
219,Vermont,USA,2020-03-15 03:00:00,5,0,0
220,Missouri,USA,2020-03-15 03:00:00,5,0,0
221,Idaho,USA,2020-03-15 03:00:00,5,0,0
222,Oklahoma,USA,2020-03-15 03:00:00,4,0,0
223,Puerto Rico,USA,2020-03-15 03:00:00,3,0,0
224,Wuhan Evacuee,USA,2020-03-15 03:00:00,3,0,0
225,Wyoming,USA,2020-03-15 03:00:00,3,0,0
226,North Dakota,USA,2020-03-15 03:00:00,1,0,0
227,United States Virgin Islands,USA,2020-03-15 03:00:00,1,0,0
228,Alaska,USA,2020-03-15 03:00:00,1,0,0

nssac-ncov-sd-03-15-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
179,Washington,USA,2020-03-16 03:00:00,769,42,1
180,New York,USA,2020-03-16 03:00:00,746,6,0
181,California,USA,2020-03-16 03:00:00,458,6,2
182,Massachusetts,USA,2020-03-16 03:00:00,164,0,1
183,Florida,USA,2020-03-16 03:00:00,149,5,0
184,Colorado,USA,2020-03-16 03:00:00,135,1,0
185,Georgia,USA,2020-03-16 03:00:00,111,1,0
186,New Jersey,USA,2020-03-16 03:00:00,109,2,0
187,Louisiana,USA,2020-03-16 03:00:00,103,2,0
188,Illinois,USA,2020-03-16 03:00:00,93,0,2
189,Texas,USA,2020-03-16 03:00:00,76,0,0
190,Pennsylvania,USA,2020-03-16 03:00:00,66,0,0
191,Michigan,USA,2020-03-16 03:00:00,53,0,0
192,Diamond Princess,USA,2020-03-16 03:00:00,47,0,0
193,Virginia,USA,2020-03-16 03:00:00,45,1,0
194,Tennessee,USA,2020-03-16 03:00:00,39,0,0
195,Oregon,USA,2020-03-16 03:00:00,39,1,0
196,Ohio,USA,2020-03-16 03:00:00,37,0,0
197,Minnesota,USA,2020-03-16 03:00:00,35,0,0
198,Maryland,USA,2020-03-16 03:00:00,34,0,0
199,Wisconsin,USA,2020-03-16 03:00:00,34,0,1
200,North Carolina,USA,2020-03-16 03:00:00,33,0,0
201,South Carolina,USA,2020-03-16 03:00:00,28,0,0
202,Utah,USA,2020-03-16 03:00:00,28,0,0
203,Connecticut,USA,2020-03-16 03:00:00,26,0,0
204,Nevada,USA,2020-03-16 03:00:00,26,0,0
205,Alabama,USA,2020-03-16 03:00:00,22,0,0
206,Iowa,USA,2020-03-16 03:00:00,22,0,0
207,Indiana,USA,2020-03-16 03:00:00,21,0,0
208,Kentucky,USA,2020-03-16 03:00:00,21,0,0
209,Grand Princess,USA,2020-03-16 03:00:00,20,0,0
210,Rhode Island,USA,2020-03-16 03:00:00,20,0,0
211,Nebraska,USA,2020-03-16 03:00:00,18,0,0
212,New Mexico,USA,2020-03-16 03:00:00,17,0,0
213,District of Columbia,USA,2020-03-16 03:00:00,17,0,0
214,Arkansas,USA,2020-03-16 03:00:00,16,0,0
215,Arizona,USA,2020-03-16 03:00:00,13,0,1
216,New Hampshire,USA,2020-03-16 03:00:00,13,0,0
217,Maine,USA,2020-03-16 03:00:00,12,0,0
218,Mississippi,USA,2020-03-16 03:00:00,10,0,0
219,South Dakota,USA,2020-03-16 03:00:00,9,1,0
220,Kansas,USA,2020-03-16 03:00:00,9,1,0
221,Vermont,USA,2020-03-16 03:00:00,8,0,0
222,Delaware,USA,2020-03-16 03:00:00,7,0,0
223,Montana,USA,2020-03-16 03:00:00,7,0,0
224,Oklahoma,USA,2020-03-16 03:00:00,7,0,0
225,Hawaii,USA,2020-03-16 03:00:00,7,0,0
226,Idaho,USA,2020-03-16 03:00:00,5,0,0
227,Missouri,USA,2020-03-16 03:00:00,5,0,0
228,Puerto Rico,USA,2020-03-16 03:00:00,5,0,0
229,Guam,USA,2020-03-16 03:00:00,3,0,0
230,Wuhan Evacuee,USA,2020-03-16 03:00:00,3,0,0
231,Wyoming,USA,2020-03-16 03:00:00,3,0,0
232,North Dakota,USA,2020-03-16 03:00:00,1,0,0
233,United States Virgin Islands,USA,2020-03-16 03:00:00,1,0,0
234,Alaska,USA,2020-03-16 03:00:00,1,0,0

nssac-ncov-sd-03-16-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
176,New York,USA,2020-03-17 02:00:00,969,10,0
177,Washington,USA,2020-03-17 03:00:00,904,48,1
178,California,USA,2020-03-17 03:00:00,567,11,2
179,Massachusetts,USA,2020-03-17 02:00:00,197,0,1
180,New Jersey,USA,2020-03-17 02:00:00,179,3,1
181,Florida,USA,2020-03-17 02:00:00,162,5,0
182,Colorado,USA,2020-03-17 02:00:00,160,1,0
183,Louisiana,USA,2020-03-17 02:00:00,136,3,0
184,Georgia,USA,2020-03-17 03:00:00,123,1,0
185,Illinois,USA,2020-03-17 03:00:00,106,0,0
186,Texas,USA,2020-03-17 03:00:00,95,1,0
187,Pennsylvania,USA,2020-03-17 03:00:00,82,0,0
188,Michigan,USA,2020-03-17 03:00:00,58,0,0
189,Minnesota,USA,2020-03-17 02:00:00,54,0,0
190,Tennessee,USA,2020-03-17 02:00:00,52,0,0
191,Virginia,USA,2020-03-17 02:00:00,52,2,0
192,Oregon,USA,2020-03-17 03:00:00,51,1,0
193,Ohio,USA,2020-03-17 02:00:00,50,0,0
194,Wisconsin,USA,2020-03-17 02:00:00,48,0,1
195,Diamond Princess,USA,2020-03-17 02:00:00,47,0,0
196,Nevada,USA,2020-03-17 02:00:00,45,1,0
197,Maryland,USA,2020-03-17 02:00:00,42,0,3
198,Connecticut,USA,2020-03-17 02:00:00,41,0,0
199,Utah,USA,2020-03-17 03:00:00,41,0,0
200,North Carolina,USA,2020-03-17 03:00:00,41,0,0
201,South Carolina,USA,2020-03-17 02:00:00,34,1,0
202,Alabama,USA,2020-03-17 02:00:00,29,0,0
203,Indiana,USA,2020-03-17 02:00:00,25,1,0
204,Kentucky,USA,2020-03-17 02:00:00,25,1,1
205,Iowa,USA,2020-03-17 02:00:00,23,0,0
206,District of Columbia,USA,2020-03-17 02:00:00,22,0,0
207,Arkansas,USA,2020-03-17 02:00:00,22,0,0
208,New Mexico,USA,2020-03-17 02:00:00,21,0,0
209,Rhode Island,USA,2020-03-17 02:00:00,21,0,0
210,Grand Princess,USA,2020-03-17 02:00:00,20,0,0
211,Nebraska,USA,2020-03-17 02:00:00,18,0,0
212,Arizona,USA,2020-03-17 02:00:00,18,0,1
213,Maine,USA,2020-03-17 02:00:00,17,0,0
214,New Hampshire,USA,2020-03-17 02:00:00,17,0,0
215,Mississippi,USA,2020-03-17 02:00:00,12,0,0
216,Vermont,USA,2020-03-17 02:00:00,12,0,0
217,Kansas,USA,2020-03-17 02:00:00,11,1,0
218,Oklahoma,USA,2020-03-17 03:00:00,10,0,0
219,Wyoming,USA,2020-03-17 03:00:00,10,0,0
220,South Dakota,USA,2020-03-17 03:00:00,10,1,0
221,Hawaii,USA,2020-03-17 02:00:00,10,0,0
222,Montana,USA,2020-03-17 02:00:00,9,0,0
223,Missouri,USA,2020-03-17 03:00:00,9,0,0
224,Delaware,USA,2020-03-17 02:00:00,8,0,0
225,Puerto Rico,USA,2020-03-17 02:00:00,5,0,0
226,Idaho,USA,2020-03-17 02:00:00,5,0,0
227,Wuhan Evacuee,USA,2020-03-17 02:00:00,3,0,0
228,Guam,USA,2020-03-17 02:00:00,3,0,0
229,Alaska,USA,2020-03-17 03:00:00,3,0,0
230,United States Virgin Islands,USA,2020-03-17 02:00:00,1,0,0
231,North Dakota,USA,2020-03-17 02:00:00,1,0,0

nssac-ncov-sd-03-17-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
187,New York,USA,2020-03-18 03:00:00,1708,16,0
188,Washington,USA,2020-03-18 03:00:00,1014,55,1
189,California,USA,2020-03-18 03:00:00,718,13,6
190,New Jersey,USA,2020-03-18 03:00:00,267,3,1
191,Massachusetts,USA,2020-03-18 03:00:00,218,0,1
192,Florida,USA,2020-03-18 03:00:00,217,7,0
193,Louisiana,USA,2020-03-18 03:00:00,196,4,0
194,Colorado,USA,2020-03-18 03:00:00,184,2,0
195,Illinois,USA,2020-03-18 03:00:00,161,1,2
196,Georgia,USA,2020-03-18 03:00:00,146,1,0
197,Texas,USA,2020-03-18 03:00:00,132,2,0
198,Pennsylvania,USA,2020-03-18 03:00:00,115,0,0
199,Wisconsin,USA,2020-03-18 03:00:00,90,0,1
200,Tennessee,USA,2020-03-18 03:00:00,78,0,0
201,Connecticut,USA,2020-03-18 03:00:00,68,0,0
202,Oregon,USA,2020-03-18 03:00:00,68,2,0
203,Ohio,USA,2020-03-18 03:00:00,67,0,0
204,Virginia,USA,2020-03-18 03:00:00,67,2,0
205,North Carolina,USA,2020-03-18 03:00:00,66,0,0
206,Michigan,USA,2020-03-18 03:00:00,65,0,0
207,Minnesota,USA,2020-03-18 03:00:00,60,0,0
208,Maryland,USA,2020-03-18 03:00:00,60,0,3
209,Nevada,USA,2020-03-18 03:00:00,56,1,0
210,Utah,USA,2020-03-18 03:00:00,51,0,0
211,Diamond Princess,USA,2020-03-18 03:00:00,47,0,0
212,South Carolina,USA,2020-03-18 03:00:00,47,1,0
213,Alabama,USA,2020-03-18 03:00:00,39,0,0
214,Maine,USA,2020-03-18 03:00:00,32,0,0
215,District of Columbia,USA,2020-03-18 03:00:00,31,0,0
216,Indiana,USA,2020-03-18 03:00:00,30,2,0
217,Iowa,USA,2020-03-18 03:00:00,29,0,0
218,Kentucky,USA,2020-03-18 03:00:00,27,1,1
219,New Hampshire,USA,2020-03-18 03:00:00,26,0,0
220,Nebraska,USA,2020-03-18 03:00:00,24,0,0
221,New Mexico,USA,2020-03-18 03:00:00,23,0,0
222,Rhode Island,USA,2020-03-18 03:00:00,23,0,0
223,Arkansas,USA,2020-03-18 03:00:00,22,0,0
224,Mississippi,USA,2020-03-18 03:00:00,21,0,0
225,Arizona,USA,2020-03-18 03:00:00,21,0,1
226,Grand Princess,USA,2020-03-18 03:00:00,21,0,0
227,Oklahoma,USA,2020-03-18 03:00:00,19,0,0
228,Kansas,USA,2020-03-18 03:00:00,18,1,0
229,Vermont,USA,2020-03-18 03:00:00,17,0,0
230,Delaware,USA,2020-03-18 03:00:00,16,0,0
231,Missouri,USA,2020-03-18 03:00:00,16,0,0
232,Wyoming,USA,2020-03-18 03:00:00,15,0,0
233,Hawaii,USA,2020-03-18 03:00:00,14,0,0
234,South Dakota,USA,2020-03-18 03:00:00,11,1,0
235,Montana,USA,2020-03-18 03:00:00,10,0,0
236,Idaho,USA,2020-03-18 03:00:00,9,0,0
237,Alaska,USA,2020-03-18 03:00:00,6,0,0
238,Guam,USA,2020-03-18 03:00:00,5,0,0
239,Puerto Rico,USA,2020-03-18 03:00:00,5,0,0
240,North Dakota,USA,2020-03-18 03:00:00,5,0,0
241,Wuhan Evacuee,USA,2020-03-18 03:00:00,3,0,0
242,United States Virgin Islands,USA,2020-03-18 03:00:00,2,0,0
243,West Virginia,USA,2020-03-18 03:00:00,1,0,0

nssac-ncov-sd-03-18-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
192,New York,USA,2020-03-19 03:00:00,3086,20,0
193,Washington,USA,2020-03-19 03:00:00,1187,68,1
194,California,USA,2020-03-19 03:00:00,864,17,6
195,New Jersey,USA,2020-03-19 03:00:00,427,5,1
196,Florida,USA,2020-03-19 03:00:00,328,8,0
197,Illinois,USA,2020-03-19 03:00:00,290,1,2
198,Louisiana,USA,2020-03-19 03:00:00,280,8,0
199,Massachusetts,USA,2020-03-19 03:00:00,256,0,1
200,Texas,USA,2020-03-19 03:00:00,223,3,0
201,Colorado,USA,2020-03-19 03:00:00,221,2,0
202,Georgia,USA,2020-03-19 03:00:00,197,4,0
203,Pennsylvania,USA,2020-03-19 03:00:00,157,1,0
204,Michigan,USA,2020-03-19 03:00:00,119,1,0
205,Wisconsin,USA,2020-03-19 03:00:00,114,0,1
206,Tennessee,USA,2020-03-19 03:00:00,100,0,0
207,Connecticut,USA,2020-03-19 03:00:00,97,1,0
208,North Carolina,USA,2020-03-19 03:00:00,92,0,0
209,Ohio,USA,2020-03-19 03:00:00,89,0,0
210,Maryland,USA,2020-03-19 03:00:00,85,1,3
211,Nevada,USA,2020-03-19 03:00:00,84,1,0
212,Virginia,USA,2020-03-19 03:00:00,79,2,0
213,Minnesota,USA,2020-03-19 03:00:00,76,0,0
214,Oregon,USA,2020-03-19 03:00:00,75,3,0
215,Utah,USA,2020-03-19 03:00:00,66,0,0
216,South Carolina,USA,2020-03-19 03:00:00,60,1,0
217,Alabama,USA,2020-03-19 03:00:00,52,0,0
218,Diamond Princess,USA,2020-03-19 03:00:00,47,0,0
219,Maine,USA,2020-03-19 03:00:00,42,0,0
220,District of Columbia,USA,2020-03-19 03:00:00,40,0,0
221,New Hampshire,USA,2020-03-19 03:00:00,39,0,0
222,Indiana,USA,2020-03-19 03:00:00,39,2,0
223,Iowa,USA,2020-03-19 03:00:00,39,0,0
224,Arkansas,USA,2020-03-19 03:00:00,37,0,0
225,Kentucky,USA,2020-03-19 03:00:00,35,1,1
226,Mississippi,USA,2020-03-19 03:00:00,34,0,0
227,Rhode Island,USA,2020-03-19 03:00:00,33,0,0
228,Oklahoma,USA,2020-03-19 03:00:00,31,0,0
229,Nebraska,USA,2020-03-19 03:00:00,29,0,0
230,Arizona,USA,2020-03-19 03:00:00,29,0,1
231,New Mexico,USA,2020-03-19 03:00:00,28,0,0
232,Delaware,USA,2020-03-19 03:00:00,26,0,0
233,Missouri,USA,2020-03-19 03:00:00,24,1,0
234,Kansas,USA,2020-03-19 03:00:00,22,1,0
235,Grand Princess,USA,2020-03-19 03:00:00,22,0,0
236,Vermont,USA,2020-03-19 03:00:00,19,0,0
237,Wyoming,USA,2020-03-19 03:00:00,18,0,0
238,Hawaii,USA,2020-03-19 03:00:00,16,0,0
239,South Dakota,USA,2020-03-19 03:00:00,11,1,0
240,Montana,USA,2020-03-19 03:00:00,11,0,0
241,Idaho,USA,2020-03-19 03:00:00,11,0,0
242,Alaska,USA,2020-03-19 03:00:00,9,0,0
243,North Dakota,USA,2020-03-19 03:00:00,7,0,0
244,Puerto Rico,USA,2020-03-19 03:00:00,5,0,0
245,Guam,USA,2020-03-19 03:00:00,5,0,0
246,Wuhan Evacuee,USA,2020-03-19 03:00:00,3,0,0
247,United States Virgin Islands,USA,2020-03-19 03:00:00,2,0,0
248,West Virginia,USA,2020-03-19 03:00:00,2,0,0

nssac-ncov-sd-03-19-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
198,New York,USA,2020-03-20 03:00:00,5712,38,0
199,Washington,USA,2020-03-20 03:00:00,1377,74,1
200,California,USA,2020-03-20 03:00:00,1041,19,6
201,New Jersey,USA,2020-03-20 03:00:00,742,9,1
202,Florida,USA,2020-03-20 03:00:00,432,9,0
203,Illinois,USA,2020-03-20 03:00:00,423,4,2
204,Louisiana,USA,2020-03-20 03:00:00,392,10,0
205,Michigan,USA,2020-03-20 03:00:00,334,3,0
206,Massachusetts,USA,2020-03-20 03:00:00,328,0,1
207,Texas,USA,2020-03-20 03:00:00,321,5,0
208,Georgia,USA,2020-03-20 03:00:00,288,10,0
209,Colorado,USA,2020-03-20 03:00:00,277,4,0
210,Pennsylvania,USA,2020-03-20 03:00:00,206,1,0
211,Wisconsin,USA,2020-03-20 03:00:00,160,2,1
212,Connecticut,USA,2020-03-20 03:00:00,159,3,0
213,Tennessee,USA,2020-03-20 03:00:00,155,0,0
214,North Carolina,USA,2020-03-20 03:00:00,139,0,0
215,Ohio,USA,2020-03-20 03:00:00,120,1,0
216,Maryland,USA,2020-03-20 03:00:00,107,1,3
217,Virginia,USA,2020-03-20 03:00:00,104,2,0
218,Nevada,USA,2020-03-20 03:00:00,95,1,0
219,Minnesota,USA,2020-03-20 03:00:00,89,0,0
220,Oregon,USA,2020-03-20 03:00:00,88,3,0
221,South Carolina,USA,2020-03-20 03:00:00,81,1,0
222,Alabama,USA,2020-03-20 03:00:00,78,0,0
223,Utah,USA,2020-03-20 03:00:00,78,0,0
224,District of Columbia,USA,2020-03-20 03:00:00,71,0,0
225,Arkansas,USA,2020-03-20 03:00:00,62,0,0
226,Indiana,USA,2020-03-20 03:00:00,61,2,0
227,Diamond Princess,USA,2020-03-20 03:00:00,55,0,0
228,Arizona,USA,2020-03-20 03:00:00,53,0,1
229,Maine,USA,2020-03-20 03:00:00,52,0,0
230,Mississippi,USA,2020-03-20 03:00:00,52,1,0
231,Kentucky,USA,2020-03-20 03:00:00,50,2,1
232,Oklahoma,USA,2020-03-20 03:00:00,44,1,0
233,Iowa,USA,2020-03-20 03:00:00,44,0,0
234,Rhode Island,USA,2020-03-20 03:00:00,44,0,0
235,New Hampshire,USA,2020-03-20 03:00:00,44,0,0
236,Missouri,USA,2020-03-20 03:00:00,41,1,0
237,Kansas,USA,2020-03-20 03:00:00,36,1,0
238,New Mexico,USA,2020-03-20 03:00:00,35,0,0
239,Nebraska,USA,2020-03-20 03:00:00,32,0,0
240,Delaware,USA,2020-03-20 03:00:00,30,0,0
241,Hawaii,USA,2020-03-20 03:00:00,26,0,0
242,Idaho,USA,2020-03-20 03:00:00,23,0,0
243,Grand Princess,USA,2020-03-20 03:00:00,23,1,0
244,Vermont,USA,2020-03-20 03:00:00,22,2,0
245,North Dakota,USA,2020-03-20 03:00:00,19,0,0
246,Wyoming,USA,2020-03-20 03:00:00,18,0,0
247,Montana,USA,2020-03-20 03:00:00,15,0,0
248,South Dakota,USA,2020-03-20 03:00:00,14,1,0
249,Guam,USA,2020-03-20 03:00:00,12,0,0
250,Alaska,USA,2020-03-20 03:00:00,12,0,0
251,Puerto Rico,USA,2020-03-20 03:00:00,5,0,0
252,West Virginia,USA,2020-03-20 03:00:00,5,0,0
253,United States Virgin Islands,USA,2020-03-20 03:00:00,3,0,0
254,Wuhan Evacuee,USA,2020-03-20 03:00:00,3,0,0

nssac-ncov-sd-03-20-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
205,New York,USA,2020-03-21 02:00:00,8403,46,0
206,Washington,USA,2020-03-21 02:00:00,1524,83,1
207,California,USA,2020-03-21 02:00:00,1247,24,6
208,New Jersey,USA,2020-03-21 02:00:00,890,11,1
209,Illinois,USA,2020-03-21 02:00:00,585,5,2
210,Florida,USA,2020-03-21 02:00:00,563,11,0
211,Michigan,USA,2020-03-21 02:00:00,552,3,0
212,Louisiana,USA,2020-03-21 02:00:00,537,14,0
213,Georgia,USA,2020-03-21 02:00:00,485,14,0
214,Texas,USA,2020-03-21 02:00:00,429,5,0
215,Massachusetts,USA,2020-03-21 02:00:00,413,1,1
216,Colorado,USA,2020-03-21 02:00:00,363,4,0
217,Pennsylvania,USA,2020-03-21 02:00:00,311,1,0
218,Tennessee,USA,2020-03-21 02:00:00,263,1,0
219,Wisconsin,USA,2020-03-21 02:00:00,210,3,1
220,Connecticut,USA,2020-03-21 02:00:00,194,4,0
221,North Carolina,USA,2020-03-21 02:00:00,188,0,0
222,Ohio,USA,2020-03-21 02:00:00,174,3,0
223,Nevada,USA,2020-03-21 02:00:00,161,2,0
224,Maryland,USA,2020-03-21 02:00:00,149,2,3
225,South Carolina,USA,2020-03-21 02:00:00,126,3,0
226,Virginia,USA,2020-03-21 02:00:00,125,2,0
227,Minnesota,USA,2020-03-21 02:00:00,115,0,0
228,Oregon,USA,2020-03-21 02:00:00,114,3,0
229,Utah,USA,2020-03-21 02:00:00,112,0,0
230,Alabama,USA,2020-03-21 02:00:00,106,0,0
231,Arkansas,USA,2020-03-21 02:00:00,96,0,0
232,Indiana,USA,2020-03-21 02:00:00,86,3,0
233,Mississippi,USA,2020-03-21 02:00:00,80,1,0
234,Arizona,USA,2020-03-21 02:00:00,79,0,1
235,District of Columbia,USA,2020-03-21 02:00:00,77,1,0
236,Missouri,USA,2020-03-21 02:00:00,66,3,0
237,Kentucky,USA,2020-03-21 02:00:00,64,2,1
238,Maine,USA,2020-03-21 02:00:00,56,0,0
239,New Hampshire,USA,2020-03-21 02:00:00,55,0,0
240,Rhode Island,USA,2020-03-21 02:00:00,54,0,0
241,Oklahoma,USA,2020-03-21 02:00:00,49,1,0
242,Diamond Princess,USA,2020-03-21 02:00:00,49,0,0
243,Kansas,USA,2020-03-21 02:00:00,48,1,0
244,Iowa,USA,2020-03-21 02:00:00,45,0,0
245,New Mexico,USA,2020-03-21 02:00:00,43,0,0
246,Delaware,USA,2020-03-21 02:00:00,39,0,0
247,Nebraska,USA,2020-03-21 02:00:00,37,0,0
248,Hawaii,USA,2020-03-21 02:00:00,37,0,0
249,Idaho,USA,2020-03-21 02:00:00,36,0,0
250,Vermont,USA,2020-03-21 02:00:00,29,2,0
251,North Dakota,USA,2020-03-21 02:00:00,26,0,0
252,Grand Princess,USA,2020-03-21 02:00:00,23,1,0
253,Wyoming,USA,2020-03-21 02:00:00,21,0,0
254,Montana,USA,2020-03-21 02:00:00,20,0,0
255,Puerto Rico,USA,2020-03-21 02:00:00,14,0,0
256,Guam,USA,2020-03-21 02:00:00,14,0,0
257,South Dakota,USA,2020-03-21 02:00:00,14,1,0
258,Alaska,USA,2020-03-21 02:00:00,12,0,0
259,West Virginia,USA,2020-03-21 02:00:00,8,0,0
260,United States Virgin Islands,USA,2020-03-21 02:00:00,3,0,0
261,Wuhan Evacuee,USA,2020-03-21 02:00:00,3,0,0

nssac-ncov-sd-03-21-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
208,USA (Aggregate Recovered),USA,2020-03-22 03:00:00,0,0,176
209,New York,USA,2020-03-22 03:00:00,12322,76,0
210,Washington,USA,2020-03-22 03:00:00,1793,94,0
211,California,USA,2020-03-22 03:00:00,1518,28,0
212,New Jersey,USA,2020-03-22 03:00:00,1327,16,0
213,Michigan,USA,2020-03-22 03:00:00,809,8,0
214,Florida,USA,2020-03-22 03:00:00,763,13,0
215,Louisiana,USA,2020-03-22 03:00:00,763,20,0
216,Illinois,USA,2020-03-22 03:00:00,753,6,0
217,Texas,USA,2020-03-22 03:00:00,557,5,0
218,Georgia,USA,2020-03-22 03:00:00,555,20,0
219,Massachusetts,USA,2020-03-22 03:00:00,529,2,0
220,Colorado,USA,2020-03-22 03:00:00,476,6,0
221,Pennsylvania,USA,2020-03-22 03:00:00,405,2,0
222,Tennessee,USA,2020-03-22 03:00:00,371,1,0
223,North Carolina,USA,2020-03-22 03:00:00,283,0,0
224,Wisconsin,USA,2020-03-22 03:00:00,282,4,0
225,Ohio,USA,2020-03-22 03:00:00,250,3,0
226,Connecticut,USA,2020-03-22 03:00:00,223,5,0
227,Maryland,USA,2020-03-22 03:00:00,194,3,0
228,South Carolina,USA,2020-03-22 03:00:00,174,3,0
229,Virginia,USA,2020-03-22 03:00:00,158,3,0
230,Nevada,USA,2020-03-22 03:00:00,157,2,0
231,Mississippi,USA,2020-03-22 03:00:00,140,1,0
232,Minnesota,USA,2020-03-22 03:00:00,137,1,0
233,Oregon,USA,2020-03-22 03:00:00,137,4,0
234,Utah,USA,2020-03-22 03:00:00,136,0,0
235,Alabama,USA,2020-03-22 03:00:00,131,0,0
236,Indiana,USA,2020-03-22 03:00:00,129,4,0
237,Arkansas,USA,2020-03-22 03:00:00,122,0,0
238,Arizona,USA,2020-03-22 03:00:00,104,1,0
239,District of Columbia,USA,2020-03-22 03:00:00,98,1,0
240,Kentucky,USA,2020-03-22 03:00:00,87,3,0
241,Missouri,USA,2020-03-22 03:00:00,86,3,0
242,Maine,USA,2020-03-22 03:00:00,70,0,0
243,Iowa,USA,2020-03-22 03:00:00,70,0,0
244,Rhode Island,USA,2020-03-22 03:00:00,66,0,0
245,New Hampshire,USA,2020-03-22 03:00:00,65,0,0
246,New Mexico,USA,2020-03-22 03:00:00,57,0,0
247,Kansas,USA,2020-03-22 03:00:00,57,2,0
248,Oklahoma,USA,2020-03-22 03:00:00,53,1,0
249,Nebraska,USA,2020-03-22 03:00:00,51,0,0
250,Vermont,USA,2020-03-22 03:00:00,49,2,0
251,Diamond Princess,USA,2020-03-22 03:00:00,49,0,0
252,Hawaii,USA,2020-03-22 03:00:00,48,0,0
253,Delaware,USA,2020-03-22 03:00:00,45,0,0
254,Idaho,USA,2020-03-22 03:00:00,42,0,0
255,Grand Princess,USA,2020-03-22 03:00:00,30,1,0
256,Montana,USA,2020-03-22 03:00:00,30,0,0
257,North Dakota,USA,2020-03-22 03:00:00,28,0,0
258,Wyoming,USA,2020-03-22 03:00:00,24,0,0
259,Alaska,USA,2020-03-22 03:00:00,21,0,0
260,Puerto Rico,USA,2020-03-22 03:00:00,21,1,0
261,Guam,USA,2020-03-22 03:00:00,15,0,0
262,South Dakota,USA,2020-03-22 03:00:00,14,1,0
263,West Virginia,USA,2020-03-22 03:00:00,12,0,0
264,United States Virgin Islands,USA,2020-03-22 03:00:00,6,0,0
265,Wuhan Evacuee,USA,2020-03-22 03:00:00,3,0,0

nssac-ncov-sd-03-22-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
211,USA (Aggregate Recovered),USA,2020-03-22 21:00:00,0,0,178
212,New York,USA,2020-03-23 03:00:00,16916,153,0
213,Washington,USA,2020-03-23 03:00:00,1996,95,0
214,New Jersey,USA,2020-03-23 03:00:00,1914,21,0
215,California,USA,2020-03-23 03:00:00,1812,35,0
216,Illinois,USA,2020-03-23 03:00:00,1050,9,0
217,Michigan,USA,2020-03-23 03:00:00,1038,9,0
218,Florida,USA,2020-03-23 03:00:00,1007,13,0
219,Louisiana,USA,2020-03-23 03:00:00,837,20,0
220,Texas,USA,2020-03-23 03:00:00,668,8,0
221,Massachusetts,USA,2020-03-23 03:00:00,646,5,0
222,Georgia,USA,2020-03-23 03:00:00,621,25,0
223,Colorado,USA,2020-03-23 03:00:00,595,7,0
224,Pennsylvania,USA,2020-03-23 03:00:00,516,5,0
225,Tennessee,USA,2020-03-23 03:00:00,505,2,0
226,Wisconsin,USA,2020-03-23 03:00:00,383,4,0
227,Ohio,USA,2020-03-23 03:00:00,356,3,0
228,Connecticut,USA,2020-03-23 03:00:00,327,8,0
229,North Carolina,USA,2020-03-23 03:00:00,311,0,0
230,Maryland,USA,2020-03-23 03:00:00,249,3,0
231,Virginia,USA,2020-03-23 03:00:00,221,6,0
232,Mississippi,USA,2020-03-23 03:00:00,207,1,0
233,Indiana,USA,2020-03-23 03:00:00,204,7,0
234,South Carolina,USA,2020-03-23 03:00:00,196,3,0
235,Nevada,USA,2020-03-23 03:00:00,191,2,0
236,Utah,USA,2020-03-23 03:00:00,181,1,0
237,Minnesota,USA,2020-03-23 03:00:00,169,1,0
238,Arkansas,USA,2020-03-23 03:00:00,165,0,0
239,Oregon,USA,2020-03-23 03:00:00,161,5,0
240,Alabama,USA,2020-03-23 03:00:00,157,0,0
241,Arizona,USA,2020-03-23 03:00:00,152,2,0
242,Missouri,USA,2020-03-23 03:00:00,150,3,0
243,District of Columbia,USA,2020-03-23 03:00:00,120,2,0
244,Kentucky,USA,2020-03-23 03:00:00,103,3,0
245,Iowa,USA,2020-03-23 03:00:00,90,0,0
246,Maine,USA,2020-03-23 03:00:00,89,0,0
247,Rhode Island,USA,2020-03-23 03:00:00,83,0,0
248,New Hampshire,USA,2020-03-23 03:00:00,78,0,0
249,Oklahoma,USA,2020-03-23 03:00:00,67,2,0
250,Kansas,USA,2020-03-23 03:00:00,67,2,0
251,New Mexico,USA,2020-03-23 03:00:00,65,0,0
252,Hawaii,USA,2020-03-23 03:00:00,56,0,0
253,Delaware,USA,2020-03-23 03:00:00,56,0,0
254,Vermont,USA,2020-03-23 03:00:00,52,2,0
255,Idaho,USA,2020-03-23 03:00:00,51,0,0
256,Nebraska,USA,2020-03-23 03:00:00,51,0,0
257,Diamond Princess,USA,2020-03-23 03:00:00,49,0,0
258,Montana,USA,2020-03-23 03:00:00,34,0,0
259,Alaska,USA,2020-03-23 03:00:00,32,0,0
260,North Dakota,USA,2020-03-23 03:00:00,30,0,0
261,Grand Princess,USA,2020-03-23 03:00:00,28,1,0
262,Guam,USA,2020-03-23 03:00:00,27,1,0
263,Wyoming,USA,2020-03-23 03:00:00,26,0,0
264,Puerto Rico,USA,2020-03-23 03:00:00,23,1,0
265,South Dakota,USA,2020-03-23 03:00:00,21,1,0
266,West Virginia,USA,2020-03-23 03:00:00,16,0,0
267,United States Virgin Islands,USA,2020-03-23 03:00:00,6,0,0
268,Wuhan Evacuee,USA,2020-03-23 03:00:00,4,0,0

nssac-ncov-sd-03-23-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
210,USA (Aggregate Recovered),USA,2020-03-24 03:00:00,0,0,333
211,New York,USA,2020-03-24 03:00:00,23230,183,0
212,New Jersey,USA,2020-03-24 03:00:00,2844,27,0
213,Washington,USA,2020-03-24 03:00:00,2221,111,0
214,California,USA,2020-03-24 03:00:00,2220,43,0
215,Michigan,USA,2020-03-24 03:00:00,1329,15,0
216,Illinois,USA,2020-03-24 03:00:00,1285,12,0
217,Florida,USA,2020-03-24 03:00:00,1227,18,0
218,Louisiana,USA,2020-03-24 03:00:00,1172,35,0
219,Texas,USA,2020-03-24 03:00:00,803,9,0
220,Georgia,USA,2020-03-24 03:00:00,803,26,0
221,Massachusetts,USA,2020-03-24 03:00:00,777,9,0
222,Colorado,USA,2020-03-24 03:00:00,723,7,0
223,Pennsylvania,USA,2020-03-24 03:00:00,698,7,0
224,Tennessee,USA,2020-03-24 03:00:00,615,2,0
225,Ohio,USA,2020-03-24 03:00:00,443,6,0
226,Wisconsin,USA,2020-03-24 03:00:00,425,5,0
227,North Carolina,USA,2020-03-24 03:00:00,420,0,0
228,Connecticut,USA,2020-03-24 03:00:00,415,10,0
229,South Carolina,USA,2020-03-24 03:00:00,298,5,0
230,Maryland,USA,2020-03-24 03:00:00,290,3,0
231,Indiana,USA,2020-03-24 03:00:00,271,7,0
232,Nevada,USA,2020-03-24 03:00:00,263,4,0
233,Utah,USA,2020-03-24 03:00:00,257,1,0
234,Virginia,USA,2020-03-24 03:00:00,254,7,0
235,Mississippi,USA,2020-03-24 03:00:00,249,1,0
236,Arizona,USA,2020-03-24 03:00:00,235,3,0
237,Minnesota,USA,2020-03-24 03:00:00,235,1,0
238,Missouri,USA,2020-03-24 03:00:00,216,5,0
239,Arkansas,USA,2020-03-24 03:00:00,197,0,0
240,Alabama,USA,2020-03-24 03:00:00,196,0,0
241,Oregon,USA,2020-03-24 03:00:00,191,5,0
242,District of Columbia,USA,2020-03-24 03:00:00,141,2,0
243,Kentucky,USA,2020-03-24 03:00:00,124,4,0
244,Maine,USA,2020-03-24 03:00:00,107,0,0
245,Rhode Island,USA,2020-03-24 03:00:00,106,0,0
246,Iowa,USA,2020-03-24 03:00:00,105,0,0
247,New Hampshire,USA,2020-03-24 03:00:00,97,1,0
248,Delaware,USA,2020-03-24 03:00:00,87,0,0
249,Kansas,USA,2020-03-24 03:00:00,85,2,0
250,New Mexico,USA,2020-03-24 03:00:00,83,0,0
251,Oklahoma,USA,2020-03-24 03:00:00,81,2,0
252,Hawaii,USA,2020-03-24 03:00:00,77,0,0
253,Vermont,USA,2020-03-24 03:00:00,75,5,0
254,Idaho,USA,2020-03-24 03:00:00,68,0,0
255,Nebraska,USA,2020-03-24 03:00:00,64,0,0
256,Diamond Princess,USA,2020-03-24 03:00:00,49,0,0
257,Montana,USA,2020-03-24 03:00:00,46,0,0
258,Puerto Rico,USA,2020-03-24 03:00:00,31,2,0
259,Alaska,USA,2020-03-24 03:00:00,36,0,0
260,North Dakota,USA,2020-03-24 03:00:00,33,0,0
261,Guam,USA,2020-03-24 03:00:00,29,1,0
262,Grand Princess,USA,2020-03-24 03:00:00,28,1,0
263,Wyoming,USA,2020-03-24 03:00:00,28,0,0
264,South Dakota,USA,2020-03-24 03:00:00,28,1,0
265,West Virginia,USA,2020-03-24 03:00:00,20,0,0
266,United States Virgin Islands,USA,2020-03-24 03:00:00,17,0,0
267,Wuhan Evacuee,USA,2020-03-24 03:00:00,4,0,0

nssac-ncov-sd-03-24-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
212,USA (Aggregate Recovered),USA,2020-03-25 03:00:00,0,0,354
213,New York,USA,2020-03-25 03:00:00,26376,271,0
214,New Jersey,USA,2020-03-25 03:00:00,3675,44,0
215,California,USA,2020-03-25 03:00:00,2628,54,0
216,Washington,USA,2020-03-25 03:00:00,2472,125,0
217,Michigan,USA,2020-03-25 03:00:00,1795,24,0
218,Illinois,USA,2020-03-25 03:00:00,1537,16,0
219,Florida,USA,2020-03-25 03:00:00,1467,23,0
220,Louisiana,USA,2020-03-25 03:00:00,1388,46,0
221,Massachusetts,USA,2020-03-25 03:00:00,1159,11,0
222,Georgia,USA,2020-03-25 03:00:00,1097,38,0
223,Texas,USA,2020-03-25 03:00:00,1027,13,0
224,Pennsylvania,USA,2020-03-25 03:00:00,946,8,0
225,Colorado,USA,2020-03-25 03:00:00,912,11,0
226,Tennessee,USA,2020-03-25 03:00:00,780,2,0
227,Connecticut,USA,2020-03-25 03:00:00,618,12,0
228,Ohio,USA,2020-03-25 03:00:00,567,8,0
229,North Carolina,USA,2020-03-25 03:00:00,512,0,0
230,Wisconsin,USA,2020-03-25 03:00:00,481,5,0
231,Indiana,USA,2020-03-25 03:00:00,369,12,0
232,Maryland,USA,2020-03-25 03:00:00,352,4,0
233,South Carolina,USA,2020-03-25 03:00:00,342,7,0
234,Arizona,USA,2020-03-25 03:00:00,326,6,0
235,Mississippi,USA,2020-03-25 03:00:00,320,1,0
236,Virginia,USA,2020-03-25 03:00:00,304,9,0
237,Utah,USA,2020-03-25 03:00:00,298,1,0
238,Nevada,USA,2020-03-25 03:00:00,285,6,0
239,Missouri,USA,2020-03-25 03:00:00,278,8,0
240,Minnesota,USA,2020-03-25 03:00:00,262,1,0
241,Alabama,USA,2020-03-25 03:00:00,242,0,0
242,Arkansas,USA,2020-03-25 03:00:00,232,2,0
243,Oregon,USA,2020-03-25 03:00:00,211,8,0
244,District of Columbia,USA,2020-03-25 03:00:00,187,2,0
245,Kentucky,USA,2020-03-25 03:00:00,163,4,0
246,Iowa,USA,2020-03-25 03:00:00,125,1,0
247,Rhode Island,USA,2020-03-25 03:00:00,124,0,0
248,Maine,USA,2020-03-25 03:00:00,118,0,0
249,New Hampshire,USA,2020-03-25 03:00:00,108,1,0
250,Oklahoma,USA,2020-03-25 03:00:00,106,3,0
251,Delaware,USA,2020-03-25 03:00:00,104,0,0
252,Kansas,USA,2020-03-25 03:00:00,102,2,0
253,New Mexico,USA,2020-03-25 03:00:00,100,0,0
254,Vermont,USA,2020-03-25 03:00:00,95,7,0
255,Hawaii,USA,2020-03-25 03:00:00,90,1,0
256,Idaho,USA,2020-03-25 03:00:00,81,0,0
257,Nebraska,USA,2020-03-25 03:00:00,71,0,0
258,Montana,USA,2020-03-25 03:00:00,51,0,0
259,Diamond Princess,USA,2020-03-25 03:00:00,49,0,0
260,Alaska,USA,2020-03-25 03:00:00,42,0,0
261,West Virginia,USA,2020-03-25 03:00:00,39,0,0
262,Puerto Rico,USA,2020-03-25 03:00:00,39,2,0
263,Wyoming,USA,2020-03-25 03:00:00,37,0,0
264,North Dakota,USA,2020-03-25 03:00:00,36,0,0
265,Guam,USA,2020-03-25 03:00:00,32,1,0
266,South Dakota,USA,2020-03-25 03:00:00,30,1,0
267,Grand Princess,USA,2020-03-25 03:00:00,28,1,0
268,United States Virgin Islands,USA,2020-03-25 03:00:00,17,0,0
269,Wuhan Evacuee,USA,2020-03-25 03:00:00,4,0,0

nssac-ncov-sd-03-25-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
215,USA (Aggregate Recovered),USA,2020-03-26 01:00:00,0,0,593
216,New York,USA,2020-03-26 03:00:00,33033,366,0
217,New Jersey,USA,2020-03-26 03:00:00,4407,62,0
218,California,USA,2020-03-26 03:00:00,3169,67,0
219,Washington,USA,2020-03-26 03:00:00,2600,133,0
220,Michigan,USA,2020-03-26 03:00:00,2297,43,0
221,Florida,USA,2020-03-26 03:00:00,1978,23,0
222,Illinois,USA,2020-03-26 03:00:00,1870,19,0
223,Massachusetts,USA,2020-03-26 03:00:00,1838,15,0
224,Louisiana,USA,2020-03-26 03:00:00,1795,65,0
225,Georgia,USA,2020-03-26 03:00:00,1387,47,0
226,Texas,USA,2020-03-26 03:00:00,1347,17,0
227,Pennsylvania,USA,2020-03-26 03:00:00,1284,15,0
228,Colorado,USA,2020-03-26 03:00:00,1087,20,0
229,Tennessee,USA,2020-03-26 03:00:00,917,3,0
230,Connecticut,USA,2020-03-26 03:00:00,875,19,0
231,Ohio,USA,2020-03-26 03:00:00,704,11,0
232,Wisconsin,USA,2020-03-26 03:00:00,638,7,0
233,North Carolina,USA,2020-03-26 03:00:00,625,2,0
234,Indiana,USA,2020-03-26 03:00:00,478,14,0
235,Alabama,USA,2020-03-26 03:00:00,439,1,0
236,Maryland,USA,2020-03-26 03:00:00,426,4,0
237,South Carolina,USA,2020-03-26 03:00:00,424,7,0
238,Nevada,USA,2020-03-26 03:00:00,405,10,0
239,Arizona,USA,2020-03-26 03:00:00,401,6,0
240,Virginia,USA,2020-03-26 03:00:00,399,13,0
241,Missouri,USA,2020-03-26 03:00:00,381,8,0
242,Mississippi,USA,2020-03-26 03:00:00,377,5,0
243,Utah,USA,2020-03-26 03:00:00,346,1,0
244,Arkansas,USA,2020-03-26 03:00:00,308,2,0
245,Minnesota,USA,2020-03-26 03:00:00,287,1,0
246,Oregon,USA,2020-03-26 03:00:00,266,10,0
247,District of Columbia,USA,2020-03-26 03:00:00,231,3,0
248,Kentucky,USA,2020-03-26 03:00:00,198,5,0
249,Oklahoma,USA,2020-03-26 03:00:00,164,6,0
250,Iowa,USA,2020-03-26 03:00:00,146,1,0
251,Maine,USA,2020-03-26 03:00:00,142,0,0
252,Idaho,USA,2020-03-26 03:00:00,138,0,0
253,Kansas,USA,2020-03-26 03:00:00,137,3,0
254,New Hampshire,USA,2020-03-26 03:00:00,137,1,0
255,Rhode Island,USA,2020-03-26 03:00:00,132,0,0
256,Vermont,USA,2020-03-26 03:00:00,125,8,0
257,Delaware,USA,2020-03-26 03:00:00,119,0,0
258,New Mexico,USA,2020-03-26 03:00:00,113,1,0
259,Hawaii,USA,2020-03-26 03:00:00,95,0,0
260,Nebraska,USA,2020-03-26 03:00:00,74,0,0
261,Montana,USA,2020-03-26 03:00:00,67,0,0
262,West Virginia,USA,2020-03-26 03:00:00,52,0,0
263,Puerto Rico,USA,2020-03-26 03:00:00,51,2,0
264,Wyoming,USA,2020-03-26 03:00:00,49,0,0
265,Diamond Princess,USA,2020-03-26 03:00:00,49,0,0
266,North Dakota,USA,2020-03-26 03:00:00,45,0,0
267,Alaska,USA,2020-03-26 03:00:00,43,1,0
268,South Dakota,USA,2020-03-26 03:00:00,41,1,0
269,Guam,USA,2020-03-26 03:00:00,37,1,0
270,Grand Princess,USA,2020-03-26 03:00:00,28,1,0
271,United States Virgin Islands,USA,2020-03-26 03:00:00,17,0,0
272,Wuhan Evacuee,USA,2020-03-26 03:00:00,4,0,0

nssac-ncov-sd-03-26-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
216,USA (Aggregate Recovered),USA,2020-03-27 01:00:00,0,0,713
217,New York,USA,2020-03-27 03:00:00,39140,461,0
218,New Jersey,USA,2020-03-27 03:00:00,6876,81,0
219,California,USA,2020-03-27 03:00:00,4040,82,0
220,Washington,USA,2020-03-27 03:00:00,3207,150,0
221,Michigan,USA,2020-03-27 03:00:00,2857,61,0
222,Illinois,USA,2020-03-27 03:00:00,2542,26,0
223,Florida,USA,2020-03-27 03:00:00,2484,29,0
224,Massachusetts,USA,2020-03-27 03:00:00,2417,25,0
225,Louisiana,USA,2020-03-27 03:00:00,2305,83,0
226,Pennsylvania,USA,2020-03-27 03:00:00,1813,18,0
227,Texas,USA,2020-03-27 03:00:00,1658,24,0
228,Georgia,USA,2020-03-27 03:00:00,1643,56,0
229,Colorado,USA,2020-03-27 03:00:00,1430,19,0
230,Tennessee,USA,2020-03-27 03:00:00,1099,3,0
231,Connecticut,USA,2020-03-27 03:00:00,1012,21,0
232,Ohio,USA,2020-03-27 03:00:00,870,15,0
233,North Carolina,USA,2020-03-27 03:00:00,755,3,0
234,Wisconsin,USA,2020-03-27 03:00:00,728,10,0
235,Indiana,USA,2020-03-27 03:00:00,657,17,0
236,Maryland,USA,2020-03-27 03:00:00,583,4,0
237,Nevada,USA,2020-03-27 03:00:00,536,10,0
238,Alabama,USA,2020-03-27 03:00:00,531,1,0
239,Missouri,USA,2020-03-27 03:00:00,530,9,0
240,Arizona,USA,2020-03-27 03:00:00,508,8,0
241,Mississippi,USA,2020-03-27 03:00:00,485,6,0
242,Virginia,USA,2020-03-27 03:00:00,471,14,0
243,South Carolina,USA,2020-03-27 03:00:00,456,9,0
244,Utah,USA,2020-03-27 03:00:00,402,1,0
245,Arkansas,USA,2020-03-27 03:00:00,349,2,0
246,Minnesota,USA,2020-03-27 03:00:00,346,2,0
247,Oregon,USA,2020-03-27 03:00:00,317,11,0
248,District of Columbia,USA,2020-03-27 03:00:00,267,3,0
249,Oklahoma,USA,2020-03-27 03:00:00,248,7,0
250,Kentucky,USA,2020-03-27 03:00:00,248,5,0
251,Idaho,USA,2020-03-27 03:00:00,191,3,0
252,Iowa,USA,2020-03-27 03:00:00,179,1,0
253,Kansas,USA,2020-03-27 03:00:00,172,3,0
254,Rhode Island,USA,2020-03-27 03:00:00,165,0,0
255,Vermont,USA,2020-03-27 03:00:00,158,9,0
256,Maine,USA,2020-03-27 03:00:00,155,0,0
257,New Hampshire,USA,2020-03-27 03:00:00,154,1,0
258,Delaware,USA,2020-03-27 03:00:00,143,1,0
259,New Mexico,USA,2020-03-27 03:00:00,136,1,0
260,Hawaii,USA,2020-03-27 03:00:00,106,0,0
261,Montana,USA,2020-03-27 03:00:00,90,1,0
262,Nebraska,USA,2020-03-27 03:00:00,82,0,0
263,West Virginia,USA,2020-03-27 03:00:00,76,0,0
264,Puerto Rico,USA,2020-03-27 03:00:00,64,2,0
265,Alaska,USA,2020-03-27 03:00:00,59,1,0
266,North Dakota,USA,2020-03-27 03:00:00,58,0,0
267,Wyoming,USA,2020-03-27 03:00:00,56,0,0
268,Diamond Princess,USA,2020-03-27 03:00:00,49,0,0
269,South Dakota,USA,2020-03-27 03:00:00,46,1,0
270,Guam,USA,2020-03-27 03:00:00,45,1,0
271,Grand Princess,USA,2020-03-27 03:00:00,28,3,0
272,United States Virgin Islands,USA,2020-03-27 03:00:00,17,0,0
273,Wuhan Evacuee,USA,2020-03-27 03:00:00,4,0,0

nssac-ncov-sd-03-27-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
216,USA (Aggregate Recovered),USA,2020-03-28 03:00:00,0,0,894
217,New York,USA,2020-03-28 03:00:00,46094,605,0
218,New Jersey,USA,2020-03-28 03:00:00,8825,108,0
219,California,USA,2020-03-28 03:00:00,4885,102,0
220,Washington,USA,2020-03-28 03:00:00,3726,175,0
221,Michigan,USA,2020-03-28 03:00:00,3657,92,0
222,Massachusetts,USA,2020-03-28 03:00:00,3240,35,0
223,Florida,USA,2020-03-28 03:00:00,3198,46,0
224,Illinois,USA,2020-03-28 03:00:00,3029,34,0
225,Louisiana,USA,2020-03-28 03:00:00,2746,119,0
226,Pennsylvania,USA,2020-03-28 03:00:00,2345,23,0
227,Georgia,USA,2020-03-28 03:00:00,2198,65,0
228,Texas,USA,2020-03-28 03:00:00,2009,26,0
229,Colorado,USA,2020-03-28 03:00:00,1740,31,0
230,Tennessee,USA,2020-03-28 03:00:00,1321,6,0
231,Connecticut,USA,2020-03-28 03:00:00,1291,27,0
232,Ohio,USA,2020-03-28 03:00:00,1139,19,0
233,Indiana,USA,2020-03-28 03:00:00,981,25,0
234,North Carolina,USA,2020-03-28 03:00:00,944,5,0
235,Wisconsin,USA,2020-03-28 03:00:00,926,14,0
236,Maryland,USA,2020-03-28 03:00:00,781,5,0
237,Missouri,USA,2020-03-28 03:00:00,709,9,0
238,Arizona,USA,2020-03-28 03:00:00,665,13,0
239,Alabama,USA,2020-03-28 03:00:00,639,4,0
240,Nevada,USA,2020-03-28 03:00:00,621,10,0
241,Virginia,USA,2020-03-28 03:00:00,610,16,0
242,Mississippi,USA,2020-03-28 03:00:00,579,8,0
243,South Carolina,USA,2020-03-28 03:00:00,542,13,0
244,Utah,USA,2020-03-28 03:00:00,480,2,0
245,Oregon,USA,2020-03-28 03:00:00,414,12,0
246,Minnesota,USA,2020-03-28 03:00:00,398,4,0
247,Arkansas,USA,2020-03-28 03:00:00,386,3,0
248,Oklahoma,USA,2020-03-28 03:00:00,322,8,0
249,District of Columbia,USA,2020-03-28 03:00:00,304,4,0
250,Kentucky,USA,2020-03-28 03:00:00,302,7,0
251,Iowa,USA,2020-03-28 03:00:00,235,3,0
252,Idaho,USA,2020-03-28 03:00:00,234,4,0
253,Kansas,USA,2020-03-28 03:00:00,219,4,0
254,Rhode Island,USA,2020-03-28 03:00:00,203,0,0
255,New Mexico,USA,2020-03-28 03:00:00,191,1,0
256,New Hampshire,USA,2020-03-28 03:00:00,187,2,0
257,Vermont,USA,2020-03-28 03:00:00,184,10,0
258,Maine,USA,2020-03-28 03:00:00,168,1,0
259,Delaware,USA,2020-03-28 03:00:00,165,2,0
260,Montana,USA,2020-03-28 03:00:00,121,1,0
261,Hawaii,USA,2020-03-28 03:00:00,120,0,0
262,Grand Princess,USA,2020-03-28 03:00:00,103,3,0
263,West Virginia,USA,2020-03-28 03:00:00,96,0,0
264,Nebraska,USA,2020-03-28 03:00:00,90,2,0
265,Alaska,USA,2020-03-28 03:00:00,85,2,0
266,Puerto Rico,USA,2020-03-28 03:00:00,79,3,0
267,Wyoming,USA,2020-03-28 03:00:00,73,0,0
268,North Dakota,USA,2020-03-28 03:00:00,68,1,0
269,South Dakota,USA,2020-03-28 03:00:00,58,1,0
270,Guam,USA,2020-03-28 03:00:00,51,1,0
271,Diamond Princess,USA,2020-03-28 03:00:00,49,0,0
272,United States Virgin Islands,USA,2020-03-28 03:00:00,19,0,0
273,Wuhan Evacuee,USA,2020-03-28 03:00:00,4,0,0

nssac-ncov-sd-03-28-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
216,USA (Aggregate Recovered),USA,2020-03-29 03:00:00,0,0,2612
217,New York,USA,2020-03-29 03:00:00,53520,834,0
218,New Jersey,USA,2020-03-29 03:00:00,11124,140,0
219,California,USA,2020-03-29 03:00:00,5648,120,0
220,Michigan,USA,2020-03-29 03:00:00,4659,112,0
221,Washington,USA,2020-03-29 03:00:00,4311,189,0
222,Massachusetts,USA,2020-03-29 03:00:00,4257,44,0
223,Florida,USA,2020-03-29 03:00:00,4038,54,0
224,Illinois,USA,2020-03-29 03:00:00,3498,47,0
225,Louisiana,USA,2020-03-29 03:00:00,3315,137,0
226,Pennsylvania,USA,2020-03-29 03:00:00,2909,35,0
227,Texas,USA,2020-03-29 03:00:00,2535,34,0
228,Georgia,USA,2020-03-29 03:00:00,2446,79,0
229,Colorado,USA,2020-03-29 03:00:00,2063,44,0
230,Connecticut,USA,2020-03-29 03:00:00,1524,33,0
231,Tennessee,USA,2020-03-29 03:00:00,1512,7,0
232,Ohio,USA,2020-03-29 03:00:00,1406,25,0
233,Indiana,USA,2020-03-29 03:00:00,1232,31,0
234,Maryland,USA,2020-03-29 03:00:00,1068,10,0
235,North Carolina,USA,2020-03-29 03:00:00,1062,5,0
236,Wisconsin,USA,2020-03-29 03:00:00,1055,17,0
237,Missouri,USA,2020-03-29 03:00:00,847,11,0
238,Arizona,USA,2020-03-29 03:00:00,773,15,0
239,Virginia,USA,2020-03-29 03:00:00,740,17,0
240,Nevada,USA,2020-03-29 03:00:00,738,14,0
241,Alabama,USA,2020-03-29 03:00:00,721,9,0
242,Mississippi,USA,2020-03-29 03:00:00,663,13,0
243,South Carolina,USA,2020-03-29 03:00:00,661,15,0
244,Utah,USA,2020-03-29 03:00:00,604,2,0
245,Oregon,USA,2020-03-29 03:00:00,479,13,0
246,Minnesota,USA,2020-03-29 03:00:00,441,5,0
247,Arkansas,USA,2020-03-29 03:00:00,409,5,0
248,Kentucky,USA,2020-03-29 03:00:00,394,9,0
249,Oklahoma,USA,2020-03-29 03:00:00,377,15,0
250,District of Columbia,USA,2020-03-29 03:00:00,342,4,0
251,Iowa,USA,2020-03-29 03:00:00,298,3,0
252,Kansas,USA,2020-03-29 03:00:00,269,5,0
253,Idaho,USA,2020-03-29 03:00:00,265,5,0
254,Rhode Island,USA,2020-03-29 03:00:00,239,2,0
255,Delaware,USA,2020-03-29 03:00:00,214,5,0
256,New Hampshire,USA,2020-03-29 03:00:00,214,2,0
257,Vermont,USA,2020-03-29 03:00:00,211,12,0
258,Maine,USA,2020-03-29 03:00:00,211,1,0
259,New Mexico,USA,2020-03-29 03:00:00,208,2,0
260,Hawaii,USA,2020-03-29 03:00:00,149,0,0
261,Montana,USA,2020-03-29 03:00:00,147,1,0
262,Puerto Rico,USA,2020-03-29 03:00:00,100,3,0
263,West Virginia,USA,2020-03-29 03:00:00,113,0,0
264,Nebraska,USA,2020-03-29 03:00:00,108,2,0
265,Grand Princess,USA,2020-03-29 03:00:00,103,3,0
266,Alaska,USA,2020-03-29 03:00:00,102,2,0
267,North Dakota,USA,2020-03-29 03:00:00,94,1,0
268,Wyoming,USA,2020-03-29 03:00:00,84,0,0
269,South Dakota,USA,2020-03-29 03:00:00,68,1,0
270,Guam,USA,2020-03-29 03:00:00,55,1,0
271,Diamond Princess,USA,2020-03-29 03:00:00,49,0,0
272,United States Virgin Islands,USA,2020-03-29 03:00:00,22,0,0
273,Wuhan Evacuee,USA,2020-03-29 03:00:00,4,0,0

nssac-ncov-sd-03-29-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
216,USA (Aggregate Recovered),USA,2020-03-30 03:00:00,0,0,4865
217,New York,USA,2020-03-30 03:00:00,59746,966,0
218,New Jersey,USA,2020-03-30 03:00:00,13386,161,0
219,California,USA,2020-03-30 03:00:00,6345,132,0
220,Michigan,USA,2020-03-30 03:00:00,5489,132,0
221,Massachusetts,USA,2020-03-30 03:00:00,4955,48,0
222,Florida,USA,2020-03-30 03:00:00,4950,60,0
223,Washington,USA,2020-03-30 03:00:00,4896,204,0
224,Illinois,USA,2020-03-30 03:00:00,4596,66,0
225,Louisiana,USA,2020-03-30 03:00:00,3540,151,0
226,Pennsylvania,USA,2020-03-30 03:00:00,3465,43,0
227,Texas,USA,2020-03-30 03:00:00,2826,37,0
228,Georgia,USA,2020-03-30 03:00:00,2683,84,0
229,Colorado,USA,2020-03-30 03:00:00,2308,47,0
230,Connecticut,USA,2020-03-30 03:00:00,1993,34,0
231,Tennessee,USA,2020-03-30 03:00:00,1818,12,0
232,Ohio,USA,2020-03-30 03:00:00,1653,29,0
233,Indiana,USA,2020-03-30 03:00:00,1514,32,0
234,Maryland,USA,2020-03-30 03:00:00,1239,15,0
235,North Carolina,USA,2020-03-30 03:00:00,1189,6,0
236,Wisconsin,USA,2020-03-30 03:00:00,1164,18,0
237,Missouri,USA,2020-03-30 03:00:00,926,13,0
238,Nevada,USA,2020-03-30 03:00:00,920,15,0
239,Arizona,USA,2020-03-30 03:00:00,919,17,0
240,Virginia,USA,2020-03-30 03:00:00,890,24,0
241,Alabama,USA,2020-03-30 03:00:00,830,10,0
242,South Carolina,USA,2020-03-30 03:00:00,774,16,0
243,Mississippi,USA,2020-03-30 03:00:00,759,14,0
244,Utah,USA,2020-03-30 03:00:00,724,4,0
245,Oregon,USA,2020-03-30 03:00:00,549,13,0
246,Minnesota,USA,2020-03-30 03:00:00,503,9,0
247,Arkansas,USA,2020-03-30 03:00:00,449,6,0
248,Kentucky,USA,2020-03-30 03:00:00,439,9,0
249,Oklahoma,USA,2020-03-30 03:00:00,431,16,0
250,District of Columbia,USA,2020-03-30 03:00:00,401,9,0
251,Iowa,USA,2020-03-30 03:00:00,336,4,0
252,Kansas,USA,2020-03-30 03:00:00,330,7,0
253,Idaho,USA,2020-03-30 03:00:00,324,6,0
254,Rhode Island,USA,2020-03-30 03:00:00,294,3,0
255,New Hampshire,USA,2020-03-30 03:00:00,258,3,0
256,Maine,USA,2020-03-30 03:00:00,253,3,0
257,New Mexico,USA,2020-03-30 03:00:00,237,2,0
258,Vermont,USA,2020-03-30 03:00:00,235,12,0
259,Delaware,USA,2020-03-30 03:00:00,232,6,0
260,Hawaii,USA,2020-03-30 03:00:00,175,0,0
261,Montana,USA,2020-03-30 03:00:00,161,2,0
262,Puerto Rico,USA,2020-03-30 03:00:00,127,5,0
263,West Virginia,USA,2020-03-30 03:00:00,124,1,0
264,Nebraska,USA,2020-03-30 03:00:00,120,2,0
265,Alaska,USA,2020-03-30 03:00:00,114,3,0
266,Grand Princess,USA,2020-03-30 03:00:00,103,3,0
267,North Dakota,USA,2020-03-30 03:00:00,98,1,0
268,South Dakota,USA,2020-03-30 03:00:00,90,1,0
269,Wyoming,USA,2020-03-30 03:00:00,87,0,0
270,Guam,USA,2020-03-30 03:00:00,56,1,0
271,Diamond Princess,USA,2020-03-30 03:00:00,49,0,0
272,United States Virgin Islands,USA,2020-03-30 03:00:00,23,0,0
273,Wuhan Evacuee,USA,2020-03-30 03:00:00,4,0,0
274,Northern Mariana Islands,USA,2020-03-30 03:00:00,2,0,0

nssac-ncov-sd-03-30-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
229,USA (Aggregate Recovered),USA,2020-03-31 03:00:00,0,0,5945
230,New York,USA,2020-03-31 03:00:00,67384,1342,0
231,New Jersey,USA,2020-03-31 03:00:00,16636,198,0
232,California,USA,2020-03-31 03:00:00,7394,149,0
233,Michigan,USA,2020-03-31 03:00:00,6498,185,0
234,Massachusetts,USA,2020-03-31 03:00:00,5752,56,0
235,Florida,USA,2020-03-31 03:00:00,5704,71,0
236,Washington,USA,2020-03-31 03:00:00,5187,219,0
237,Illinois,USA,2020-03-31 03:00:00,5058,74,0
238,Pennsylvania,USA,2020-03-31 03:00:00,4155,51,0
239,Louisiana,USA,2020-03-31 03:00:00,4025,185,0
240,Texas,USA,2020-03-31 03:00:00,3346,48,0
241,Georgia,USA,2020-03-31 03:00:00,3032,102,0
242,Colorado,USA,2020-03-31 03:00:00,2627,51,0
243,Connecticut,USA,2020-03-31 03:00:00,2571,36,0
244,Tennessee,USA,2020-03-31 03:00:00,1937,14,0
245,Ohio,USA,2020-03-31 03:00:00,1933,40,0
246,Indiana,USA,2020-03-31 03:00:00,1787,35,0
247,Maryland,USA,2020-03-31 03:00:00,1413,15,0
248,North Carolina,USA,2020-03-31 03:00:00,1379,8,0
249,Wisconsin,USA,2020-03-31 03:00:00,1285,24,0
250,Arizona,USA,2020-03-31 03:00:00,1158,20,0
251,Missouri,USA,2020-03-31 03:00:00,1122,13,0
252,Nevada,USA,2020-03-31 03:00:00,1044,18,0
253,Virginia,USA,2020-03-31 03:00:00,1020,25,0
254,Alabama,USA,2020-03-31 03:00:00,947,11,0
255,South Carolina,USA,2020-03-31 03:00:00,925,18,0
256,Mississippi,USA,2020-03-31 03:00:00,847,16,0
257,Utah,USA,2020-03-31 03:00:00,806,4,0
258,Oregon,USA,2020-03-31 03:00:00,606,16,0
259,Minnesota,USA,2020-03-31 03:00:00,576,10,0
260,Arkansas,USA,2020-03-31 03:00:00,508,7,0
261,District of Columbia,USA,2020-03-31 03:00:00,495,9,0
262,Oklahoma,USA,2020-03-31 03:00:00,483,17,0
263,Kentucky,USA,2020-03-31 03:00:00,480,11,0
264,Idaho,USA,2020-03-31 03:00:00,431,8,0
265,Iowa,USA,2020-03-31 03:00:00,424,6,0
266,Rhode Island,USA,2020-03-31 03:00:00,408,4,0
267,Kansas,USA,2020-03-31 03:00:00,374,8,0
268,New Hampshire,USA,2020-03-31 03:00:00,314,3,0
269,New Mexico,USA,2020-03-31 03:00:00,281,4,0
270,Maine,USA,2020-03-31 03:00:00,275,3,0
271,Delaware,USA,2020-03-31 03:00:00,264,7,0
272,Vermont,USA,2020-03-31 03:00:00,256,12,0
273,Hawaii,USA,2020-03-31 03:00:00,204,0,0
274,Montana,USA,2020-03-31 03:00:00,177,5,0
275,Puerto Rico,USA,2020-03-31 03:00:00,174,7,0
276,Nebraska,USA,2020-03-31 03:00:00,153,3,0
277,West Virginia,USA,2020-03-31 03:00:00,145,1,0
278,Alaska,USA,2020-03-31 03:00:00,119,3,0
279,North Dakota,USA,2020-03-31 03:00:00,109,3,0
280,Grand Princess,USA,2020-03-31 03:00:00,103,3,0
281,South Dakota,USA,2020-03-31 03:00:00,101,1,0
282,Wyoming,USA,2020-03-31 03:00:00,95,0,0
283,Guam,USA,2020-03-31 03:00:00,58,1,0
284,Diamond Princess,USA,2020-03-31 03:00:00,49,0,0
285,United States Virgin Islands,USA,2020-03-31 03:00:00,30,0,0
286,Wuhan Evacuee,USA,2020-03-31 03:00:00,4,0,0
287,Northern Mariana Islands,USA,2020-03-31 03:00:00,2,0,0

nssac-ncov-sd-03-31-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
231,USA (Aggregate Recovered),USA,2020-04-01 03:00:00,0,0,7136
232,New York,USA,2020-04-01 03:00:00,76049,1714,0
233,New Jersey,USA,2020-04-01 03:00:00,18997,267,0
234,California,USA,2020-04-01 03:00:00,8558,182,0
235,Michigan,USA,2020-04-01 03:00:00,7615,259,0
236,Florida,USA,2020-04-01 03:00:00,6741,85,0
237,Massachusetts,USA,2020-04-01 03:00:00,6620,89,0
238,Illinois,USA,2020-04-01 03:00:00,5998,100,0
239,Washington,USA,2020-04-01 03:00:00,5453,225,0
240,Louisiana,USA,2020-04-01 03:00:00,5237,239,0
241,Pennsylvania,USA,2020-04-01 03:00:00,4994,67,0
242,Georgia,USA,2020-04-01 03:00:00,4117,125,0
243,Texas,USA,2020-04-01 03:00:00,3925,58,0
244,Connecticut,USA,2020-04-01 03:00:00,3128,69,0
245,Colorado,USA,2020-04-01 03:00:00,2968,69,0
246,Tennessee,USA,2020-04-01 03:00:00,2391,23,0
247,Ohio,USA,2020-04-01 03:00:00,2199,55,0
248,Indiana,USA,2020-04-01 03:00:00,2159,49,0
249,Maryland,USA,2020-04-01 03:00:00,1660,19,0
250,North Carolina,USA,2020-04-01 03:00:00,1561,12,0
251,Wisconsin,USA,2020-04-01 03:00:00,1412,25,0
252,Missouri,USA,2020-04-01 03:00:00,1407,15,0
253,Arizona,USA,2020-04-01 03:00:00,1289,24,0
254,Virginia,USA,2020-04-01 03:00:00,1250,27,0
255,Nevada,USA,2020-04-01 03:00:00,1138,26,0
256,South Carolina,USA,2020-04-01 03:00:00,1083,22,0
257,Alabama,USA,2020-04-01 03:00:00,999,24,0
258,Mississippi,USA,2020-04-01 03:00:00,937,20,0
259,Utah,USA,2020-04-01 03:00:00,888,5,0
260,Oregon,USA,2020-04-01 03:00:00,690,18,0
261,Kentucky,USA,2020-04-01 03:00:00,632,18,0
262,Minnesota,USA,2020-04-01 03:00:00,629,12,0
263,Oklahoma,USA,2020-04-01 03:00:00,568,23,0
264,Arkansas,USA,2020-04-01 03:00:00,564,8,0
265,Idaho,USA,2020-04-01 03:00:00,525,9,0
266,District of Columbia,USA,2020-04-01 03:00:00,507,9,0
267,Iowa,USA,2020-04-01 03:00:00,497,7,0
268,Rhode Island,USA,2020-04-01 03:00:00,488,8,0
269,Kansas,USA,2020-04-01 03:00:00,441,9,0
270,New Hampshire,USA,2020-04-01 03:00:00,367,3,0
271,Delaware,USA,2020-04-01 03:00:00,319,10,0
272,New Mexico,USA,2020-04-01 03:00:00,316,5,0
273,Maine,USA,2020-04-01 03:00:00,303,5,0
274,Vermont,USA,2020-04-01 03:00:00,293,13,0
275,Puerto Rico,USA,2020-04-01 03:00:00,239,8,0
276,Hawaii,USA,2020-04-01 03:00:00,224,1,0
277,Montana,USA,2020-04-01 03:00:00,198,5,0
278,Nebraska,USA,2020-04-01 03:00:00,177,4,0
279,West Virginia,USA,2020-04-01 03:00:00,162,1,0
280,Navajo Nation,USA,2020-04-01 03:00:00,148,5,0
281,Alaska,USA,2020-04-01 03:00:00,133,3,0
282,North Dakota,USA,2020-04-01 03:00:00,122,3,0
283,Wyoming,USA,2020-04-01 03:00:00,120,0,0
284,South Dakota,USA,2020-04-01 03:00:00,108,1,0
285,Grand Princess,USA,2020-04-01 03:00:00,103,3,0
286,Guam,USA,2020-04-01 03:00:00,69,2,0
287,Diamond Princess,USA,2020-04-01 03:00:00,49,0,0
288,United States Virgin Islands,USA,2020-04-01 03:00:00,30,0,0
289,Wuhan Evacuee,USA,2020-04-01 03:00:00,4,0,0
290,Northern Mariana Islands,USA,2020-04-01 03:00:00,2,0,0

nssac-ncov-sd-04-01-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
231,USA (Aggregate Recovered),USA,2020-04-02 03:00:00,0,0,8672
232,New York,USA,2020-04-02 03:00:00,84046,2220,0
233,New Jersey,USA,2020-04-02 03:00:00,22255,355,0
234,California,USA,2020-04-02 03:00:00,9907,216,0
235,Michigan,USA,2020-04-02 03:00:00,9334,337,0
236,Florida,USA,2020-04-02 03:00:00,7773,101,0
237,Massachusetts,USA,2020-04-02 03:00:00,7738,122,0
238,Illinois,USA,2020-04-02 03:00:00,6980,146,0
239,Louisiana,USA,2020-04-02 03:00:00,6424,273,0
240,Pennsylvania,USA,2020-04-02 03:00:00,6063,74,0
241,Washington,USA,2020-04-02 03:00:00,5984,254,0
242,Georgia,USA,2020-04-02 03:00:00,4748,154,0
243,Texas,USA,2020-04-02 03:00:00,4607,68,0
244,Connecticut,USA,2020-04-02 03:00:00,3557,85,0
245,Colorado,USA,2020-04-02 03:00:00,3342,80,0
246,Tennessee,USA,2020-04-02 03:00:00,2933,24,0
247,Indiana,USA,2020-04-02 03:00:00,2569,65,0
248,Ohio,USA,2020-04-02 03:00:00,2547,65,0
249,Maryland,USA,2020-04-02 03:00:00,1986,31,0
250,North Carolina,USA,2020-04-02 03:00:00,1768,16,0
251,Missouri,USA,2020-04-02 03:00:00,1672,22,0
252,Wisconsin,USA,2020-04-02 03:00:00,1573,28,0
253,Virginia,USA,2020-04-02 03:00:00,1486,35,0
254,Arizona,USA,2020-04-02 03:00:00,1413,29,0
255,Nevada,USA,2020-04-02 03:00:00,1299,32,0
256,South Carolina,USA,2020-04-02 03:00:00,1293,26,0
257,Alabama,USA,2020-04-02 03:00:00,1107,28,0
258,Mississippi,USA,2020-04-02 03:00:00,1073,22,0
259,Utah,USA,2020-04-02 03:00:00,1012,7,0
260,Oregon,USA,2020-04-02 03:00:00,736,19,0
261,Oklahoma,USA,2020-04-02 03:00:00,721,30,0
262,Minnesota,USA,2020-04-02 03:00:00,689,17,0
263,Kentucky,USA,2020-04-02 03:00:00,687,20,0
264,Idaho,USA,2020-04-02 03:00:00,669,9,0
265,Arkansas,USA,2020-04-02 03:00:00,624,10,0
266,District of Columbia,USA,2020-04-02 03:00:00,586,11,0
267,Rhode Island,USA,2020-04-02 03:00:00,566,10,0
268,Iowa,USA,2020-04-02 03:00:00,552,9,0
269,Kansas,USA,2020-04-02 03:00:00,495,10,0
270,New Hampshire,USA,2020-04-02 03:00:00,415,4,0
271,Delaware,USA,2020-04-02 03:00:00,368,11,0
272,New Mexico,USA,2020-04-02 03:00:00,363,6,0
273,Maine,USA,2020-04-02 03:00:00,344,7,0
274,Vermont,USA,2020-04-02 03:00:00,321,16,0
275,Puerto Rico,USA,2020-04-02 03:00:00,286,11,0
276,Hawaii,USA,2020-04-02 03:00:00,256,1,0
277,Montana,USA,2020-04-02 03:00:00,217,6,0
278,Nebraska,USA,2020-04-02 03:00:00,214,4,0
279,West Virginia,USA,2020-04-02 03:00:00,191,2,0
280,Navajo Nation,USA,2020-04-02 03:00:00,148,5,0
281,North Dakota,USA,2020-04-02 03:00:00,147,3,0
282,Alaska,USA,2020-04-02 03:00:00,143,3,0
283,Wyoming,USA,2020-04-02 03:00:00,137,0,0
284,South Dakota,USA,2020-04-02 03:00:00,129,2,0
285,Grand Princess,USA,2020-04-02 03:00:00,103,3,0
286,Guam,USA,2020-04-02 03:00:00,77,3,0
287,Diamond Princess,USA,2020-04-02 03:00:00,49,0,0
288,United States Virgin Islands,USA,2020-04-02 03:00:00,30,0,0
289,Northern Mariana Islands,USA,2020-04-02 03:00:00,6,1,0
290,Wuhan Evacuee,USA,2020-04-02 03:00:00,4,0,0

nssac-ncov-sd-04-02-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
232,USA (Aggregate Recovered),USA,2020-04-03 03:00:00,0,0,9228
233,New York,USA,2020-04-03 03:00:00,92743,2468,0
234,New Jersey,USA,2020-04-03 03:00:00,25590,537,0
235,California,USA,2020-04-03 03:00:00,11126,244,0
236,Michigan,USA,2020-04-03 03:00:00,10791,417,0
237,Louisiana,USA,2020-04-03 03:00:00,9159,310,0
238,Florida,USA,2020-04-03 03:00:00,9008,144,0
239,Massachusetts,USA,2020-04-03 03:00:00,8966,154,0
240,Illinois,USA,2020-04-03 03:00:00,7697,167,0
241,Pennsylvania,USA,2020-04-03 03:00:00,7345,92,0
242,Washington,USA,2020-04-03 03:00:00,6595,272,0
243,Georgia,USA,2020-04-03 03:00:00,5444,176,0
244,Texas,USA,2020-04-03 03:00:00,5253,86,0
245,Connecticut,USA,2020-04-03 03:00:00,3824,112,0
246,Colorado,USA,2020-04-03 03:00:00,3728,97,0
247,Indiana,USA,2020-04-03 03:00:00,3039,78,0
248,Ohio,USA,2020-04-03 03:00:00,2902,81,0
249,Tennessee,USA,2020-04-03 03:00:00,2845,36,0
250,Maryland,USA,2020-04-03 03:00:00,2331,36,0
251,North Carolina,USA,2020-04-03 03:00:00,2041,21,0
252,Missouri,USA,2020-04-03 03:00:00,1860,22,0
253,Wisconsin,USA,2020-04-03 03:00:00,1748,38,0
254,Virginia,USA,2020-04-03 03:00:00,1706,41,0
255,Arizona,USA,2020-04-03 03:00:00,1598,32,0
256,South Carolina,USA,2020-04-03 03:00:00,1554,31,0
257,Nevada,USA,2020-04-03 03:00:00,1484,38,0
258,Alabama,USA,2020-04-03 03:00:00,1270,32,0
259,Mississippi,USA,2020-04-03 03:00:00,1177,26,0
260,Utah,USA,2020-04-03 03:00:00,1088,7,0
261,Idaho,USA,2020-04-03 03:00:00,891,9,0
262,Oklahoma,USA,2020-04-03 03:00:00,881,34,0
263,Oregon,USA,2020-04-03 03:00:00,826,21,0
264,Kentucky,USA,2020-04-03 03:00:00,770,31,0
265,Minnesota,USA,2020-04-03 03:00:00,742,18,0
266,Arkansas,USA,2020-04-03 03:00:00,683,12,0
267,Rhode Island,USA,2020-04-03 03:00:00,657,12,0
268,District of Columbia,USA,2020-04-03 03:00:00,653,12,0
269,Iowa,USA,2020-04-03 03:00:00,614,11,0
270,Kansas,USA,2020-04-03 03:00:00,558,14,0
271,New Hampshire,USA,2020-04-03 03:00:00,479,5,0
272,New Mexico,USA,2020-04-03 03:00:00,403,7,0
273,Delaware,USA,2020-04-03 03:00:00,393,12,0
274,Maine,USA,2020-04-03 03:00:00,376,7,0
275,Vermont,USA,2020-04-03 03:00:00,338,17,0
276,Puerto Rico,USA,2020-04-03 03:00:00,316,12,0
277,Hawaii,USA,2020-04-03 03:00:00,283,2,0
278,Nebraska,USA,2020-04-03 03:00:00,255,6,0
279,Montana,USA,2020-04-03 03:00:00,241,5,0
280,Navajo Nation,USA,2020-04-03 03:00:00,241,7,0
281,West Virginia,USA,2020-04-03 03:00:00,217,2,0
282,South Dakota,USA,2020-04-03 03:00:00,165,2,0
283,North Dakota,USA,2020-04-03 03:00:00,159,3,0
284,Wyoming,USA,2020-04-03 03:00:00,153,0,0
285,Alaska,USA,2020-04-03 03:00:00,147,3,0
286,Grand Princess,USA,2020-04-03 03:00:00,103,3,0
287,Guam,USA,2020-04-03 03:00:00,82,3,0
288,Diamond Princess,USA,2020-04-03 03:00:00,49,0,0
289,United States Virgin Islands,USA,2020-04-03 03:00:00,37,0,0
290,Northern Mariana Islands,USA,2020-04-03 03:00:00,8,1,0
291,Wuhan Evacuee,USA,2020-04-03 03:00:00,4,0,0

nssac-ncov-sd-04-03-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
232,USA (Aggregate Recovered),USA,2020-04-04 03:00:00,0,0,9897
233,New York,USA,2020-04-04 03:00:00,103169,2935,0
234,New Jersey,USA,2020-04-04 03:00:00,29895,646,0
235,Michigan,USA,2020-04-04 03:00:00,12744,479,0
236,California,USA,2020-04-04 03:00:00,12507,280,0
237,Massachusetts,USA,2020-04-04 03:00:00,10402,192,0
238,Louisiana,USA,2020-04-04 03:00:00,10297,370,0
239,Florida,USA,2020-04-04 03:00:00,10268,170,0
240,Illinois,USA,2020-04-04 03:00:00,9266,210,0
241,Pennsylvania,USA,2020-04-04 03:00:00,8570,102,0
242,Washington,USA,2020-04-04 03:00:00,6967,295,0
243,Texas,USA,2020-04-04 03:00:00,6030,104,0
244,Georgia,USA,2020-04-04 03:00:00,5967,198,0
245,Connecticut,USA,2020-04-04 03:00:00,4914,131,0
246,Colorado,USA,2020-04-04 03:00:00,4181,111,0
247,Indiana,USA,2020-04-04 03:00:00,3437,102,0
248,Ohio,USA,2020-04-04 03:00:00,3312,91,0
249,Tennessee,USA,2020-04-04 03:00:00,3068,44,0
250,Maryland,USA,2020-04-04 03:00:00,2758,43,0
251,North Carolina,USA,2020-04-04 03:00:00,2336,30,0
252,Missouri,USA,2020-04-04 03:00:00,2158,33,0
253,Wisconsin,USA,2020-04-04 03:00:00,2012,51,0
254,Virginia,USA,2020-04-04 03:00:00,2012,47,0
255,Arizona,USA,2020-04-04 03:00:00,1769,41,0
256,South Carolina,USA,2020-04-04 03:00:00,1700,34,0
257,Nevada,USA,2020-04-04 03:00:00,1559,43,0
258,Alabama,USA,2020-04-04 03:00:00,1535,38,0
259,Mississippi,USA,2020-04-04 03:00:00,1358,29,0
260,Utah,USA,2020-04-04 03:00:00,1248,7,0
261,Idaho,USA,2020-04-04 03:00:00,1013,10,0
262,Oklahoma,USA,2020-04-04 03:00:00,990,38,0
263,Oregon,USA,2020-04-04 03:00:00,899,22,0
264,Kentucky,USA,2020-04-04 03:00:00,831,37,0
265,Minnesota,USA,2020-04-04 03:00:00,789,22,0
266,District of Columbia,USA,2020-04-04 03:00:00,757,15,0
267,Arkansas,USA,2020-04-04 03:00:00,738,12,0
268,Rhode Island,USA,2020-04-04 03:00:00,711,14,0
269,Iowa,USA,2020-04-04 03:00:00,699,11,0
270,Kansas,USA,2020-04-04 03:00:00,629,18,0
271,New Hampshire,USA,2020-04-04 03:00:00,540,7,0
272,New Mexico,USA,2020-04-04 03:00:00,495,10,0
273,Delaware,USA,2020-04-04 03:00:00,450,14,0
274,Maine,USA,2020-04-04 03:00:00,432,9,0
275,Vermont,USA,2020-04-04 03:00:00,389,17,0
276,Puerto Rico,USA,2020-04-04 03:00:00,378,15,0
277,Hawaii,USA,2020-04-04 03:00:00,319,3,0
278,Nebraska,USA,2020-04-04 03:00:00,285,6,0
279,Montana,USA,2020-04-04 03:00:00,262,5,0
280,Navajo Nation,USA,2020-04-04 03:00:00,241,7,0
281,West Virginia,USA,2020-04-04 03:00:00,237,2,0
282,South Dakota,USA,2020-04-04 03:00:00,187,2,0
283,North Dakota,USA,2020-04-04 03:00:00,173,3,0
284,Wyoming,USA,2020-04-04 03:00:00,166,0,0
285,Alaska,USA,2020-04-04 03:00:00,157,3,0
286,Grand Princess,USA,2020-04-04 03:00:00,103,3,0
287,Guam,USA,2020-04-04 03:00:00,84,4,0
288,Diamond Princess,USA,2020-04-04 03:00:00,49,0,0
289,United States Virgin Islands,USA,2020-04-04 03:00:00,38,0,0
290,Northern Mariana Islands,USA,2020-04-04 03:00:00,8,1,0
291,Wuhan Evacuee,USA,2020-04-04 03:00:00,4,0,0

nssac-ncov-sd-04-04-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
233,USA (Aggregate Recovered),USA,2020-04-05 03:00:00,0,0,15021
234,New York,USA,2020-04-05 03:00:00,114174,3565,0
235,New Jersey,USA,2020-04-05 03:00:00,34124,846,0
236,Michigan,USA,2020-04-05 03:00:00,14225,540,0
237,California,USA,2020-04-05 03:00:00,13904,324,0
238,Louisiana,USA,2020-04-05 03:00:00,12496,409,0
239,Massachusetts,USA,2020-04-05 03:00:00,11736,216,0
240,Florida,USA,2020-04-05 03:00:00,11545,195,0
241,Pennsylvania,USA,2020-04-05 03:00:00,10507,139,0
242,Illinois,USA,2020-04-05 03:00:00,10360,245,0
243,Washington,USA,2020-04-05 03:00:00,7632,318,0
244,Texas,USA,2020-04-05 03:00:00,6872,122,0
245,Georgia,USA,2020-04-05 03:00:00,6383,208,0
246,Connecticut,USA,2020-04-05 03:00:00,5276,165,0
247,Colorado,USA,2020-04-05 03:00:00,4565,126,0
248,Indiana,USA,2020-04-05 03:00:00,3953,116,0
249,Ohio,USA,2020-04-05 03:00:00,3739,102,0
250,Tennessee,USA,2020-04-05 03:00:00,3322,50,0
251,Maryland,USA,2020-04-05 03:00:00,3172,54,0
252,North Carolina,USA,2020-04-05 03:00:00,2549,35,0
253,Virginia,USA,2020-04-05 03:00:00,2407,52,0
254,Missouri,USA,2020-04-05 03:00:00,2345,43,0
255,Wisconsin,USA,2020-04-05 03:00:00,2128,60,0
256,Arizona,USA,2020-04-05 03:00:00,2019,52,0
257,South Carolina,USA,2020-04-05 03:00:00,1917,40,0
258,Nevada,USA,2020-04-05 03:00:00,1742,46,0
259,Alabama,USA,2020-04-05 03:00:00,1633,44,0
260,Mississippi,USA,2020-04-05 03:00:00,1455,35,0
261,Utah,USA,2020-04-05 03:00:00,1429,8,0
262,Oklahoma,USA,2020-04-05 03:00:00,1161,42,0
263,Idaho,USA,2020-04-05 03:00:00,1078,10,0
264,Oregon,USA,2020-04-05 03:00:00,999,26,0
265,Kentucky,USA,2020-04-05 03:00:00,917,40,0
266,District of Columbia,USA,2020-04-05 03:00:00,902,21,0
267,Minnesota,USA,2020-04-05 03:00:00,865,24,0
268,Rhode Island,USA,2020-04-05 03:00:00,806,17,0
269,Iowa,USA,2020-04-05 03:00:00,787,14,0
270,Arkansas,USA,2020-04-05 03:00:00,743,14,0
271,Kansas,USA,2020-04-05 03:00:00,698,21,0
272,New Hampshire,USA,2020-04-05 03:00:00,621,9,0
273,Delaware,USA,2020-04-05 03:00:00,593,14,0
274,New Mexico,USA,2020-04-05 03:00:00,543,11,0
275,Vermont,USA,2020-04-05 03:00:00,461,20,0
276,Maine,USA,2020-04-05 03:00:00,456,10,0
277,Puerto Rico,USA,2020-04-05 03:00:00,452,18,0
278,Hawaii,USA,2020-04-05 03:00:00,351,3,0
279,Nebraska,USA,2020-04-05 03:00:00,323,8,0
280,West Virginia,USA,2020-04-05 03:00:00,282,2,0
281,Montana,USA,2020-04-05 03:00:00,281,6,0
282,Navajo Nation,USA,2020-04-05 03:00:00,270,12,0
283,South Dakota,USA,2020-04-05 03:00:00,212,2,0
284,Wyoming,USA,2020-04-05 03:00:00,187,0,0
285,North Dakota,USA,2020-04-05 03:00:00,186,3,0
286,Alaska,USA,2020-04-05 03:00:00,171,5,0
287,Grand Princess,USA,2020-04-05 03:00:00,103,3,0
288,Guam,USA,2020-04-05 03:00:00,93,4,0
289,Diamond Princess,USA,2020-04-05 03:00:00,49,0,0
290,United States Virgin Islands,USA,2020-04-05 03:00:00,42,0,0
291,Northern Mariana Islands,USA,2020-04-05 03:00:00,8,1,0
292,Wuhan Evacuee,USA,2020-04-05 03:00:00,4,0,0

nssac-ncov-sd-04-05-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
235,USA (Aggregate Recovered),USA,2020-04-06 03:00:00,0,0,17582
236,New York,USA,2020-04-06 03:00:00,123160,4159,0
237,New Jersey,USA,2020-04-06 03:00:00,37505,917,0
238,Michigan,USA,2020-04-06 03:00:00,15718,617,0
239,California,USA,2020-04-06 03:00:00,15158,350,0
240,Louisiana,USA,2020-04-06 03:00:00,13010,477,0
241,Massachusetts,USA,2020-04-06 03:00:00,12500,231,0
242,Florida,USA,2020-04-06 03:00:00,12350,221,0
243,Pennsylvania,USA,2020-04-06 03:00:00,11589,151,0
244,Illinois,USA,2020-04-06 03:00:00,11260,276,0
245,Washington,USA,2020-04-06 03:00:00,7984,343,0
246,Texas,USA,2020-04-06 03:00:00,7294,140,0
247,Georgia,USA,2020-04-06 03:00:00,6742,219,0
248,Connecticut,USA,2020-04-06 03:00:00,5675,189,0
249,Colorado,USA,2020-04-06 03:00:00,4950,140,0
250,Indiana,USA,2020-04-06 03:00:00,4411,127,0
251,Ohio,USA,2020-04-06 03:00:00,4043,119,0
252,Tennessee,USA,2020-04-06 03:00:00,3633,53,0
253,Maryland,USA,2020-04-06 03:00:00,3617,67,0
254,North Carolina,USA,2020-04-06 03:00:00,2683,41,0
255,Virginia,USA,2020-04-06 03:00:00,2640,52,0
256,Missouri,USA,2020-04-06 03:00:00,2464,47,0
257,Wisconsin,USA,2020-04-06 03:00:00,2320,75,0
258,Arizona,USA,2020-04-06 03:00:00,2269,64,0
259,South Carolina,USA,2020-04-06 03:00:00,2049,44,0
260,Alabama,USA,2020-04-06 03:00:00,1841,45,0
261,Nevada,USA,2020-04-06 03:00:00,1836,46,0
262,Mississippi,USA,2020-04-06 03:00:00,1638,43,0
263,Utah,USA,2020-04-06 03:00:00,1605,8,0
264,Oklahoma,USA,2020-04-06 03:00:00,1254,46,0
265,Idaho,USA,2020-04-06 03:00:00,1101,10,0
266,Oregon,USA,2020-04-06 03:00:00,1068,27,0
267,District of Columbia,USA,2020-04-06 03:00:00,1002,22,0
268,Kentucky,USA,2020-04-06 03:00:00,955,45,0
269,Minnesota,USA,2020-04-06 03:00:00,935,29,0
270,Rhode Island,USA,2020-04-06 03:00:00,922,25,0
271,Iowa,USA,2020-04-06 03:00:00,869,22,0
272,Arkansas,USA,2020-04-06 03:00:00,853,16,0
273,Kansas,USA,2020-04-06 03:00:00,759,22,0
274,Delaware,USA,2020-04-06 03:00:00,673,14,0
275,New Hampshire,USA,2020-04-06 03:00:00,669,9,0
276,New Mexico,USA,2020-04-06 03:00:00,624,12,0
277,Vermont,USA,2020-04-06 03:00:00,512,22,0
278,Puerto Rico,USA,2020-04-06 03:00:00,475,20,0
279,Maine,USA,2020-04-06 03:00:00,470,10,0
280,Hawaii,USA,2020-04-06 03:00:00,371,4,0
281,Nebraska,USA,2020-04-06 03:00:00,364,8,0
282,Navajo Nation,USA,2020-04-06 03:00:00,354,14,0
283,West Virginia,USA,2020-04-06 03:00:00,324,3,0
284,Montana,USA,2020-04-06 03:00:00,298,6,0
285,South Dakota,USA,2020-04-06 03:00:00,240,2,0
286,North Dakota,USA,2020-04-06 03:00:00,207,3,0
287,Wyoming,USA,2020-04-06 03:00:00,200,0,0
288,Alaska,USA,2020-04-06 03:00:00,185,6,0
289,Guam,USA,2020-04-06 03:00:00,112,4,0
290,Grand Princess,USA,2020-04-06 03:00:00,103,3,0
291,Diamond Princess,USA,2020-04-06 03:00:00,49,0,0
292,United States Virgin Islands,USA,2020-04-06 03:00:00,42,1,0
293,Northern Mariana Islands,USA,2020-04-06 03:00:00,8,1,0
294,Wuhan Evacuee,USA,2020-04-06 03:00:00,4,0,0

nssac-ncov-sd-04-06-2020.csv

,name,Region,Last Update,Confirmed,Deaths,Recovered
236,USA (Aggregate Recovered),USA,2020-04-07 01:00:00,0,0,19577
237,New York,USA,2020-04-07 01:00:00,131815,4758,0
238,New Jersey,USA,2020-04-07 01:00:00,41090,1003,0
239,Michigan,USA,2020-04-07 01:00:00,17221,727,0
240,California,USA,2020-04-07 01:00:00,16211,386,0
241,Louisiana,USA,2020-04-07 01:00:00,14867,512,0
242,Massachusetts,USA,2020-04-07 01:00:00,13837,260,0
243,Florida,USA,2020-04-07 01:00:00,13629,254,0
244,Pennsylvania,USA,2020-04-07 01:00:00,13127,179,0
245,Illinois,USA,2020-04-07 01:00:00,12262,308,0
246,Washington,USA,2020-04-07 01:00:00,8341,383,0
247,Texas,USA,2020-04-07 01:00:00,8138,152,0
248,Georgia,USA,2020-04-07 01:00:00,7314,229,0
249,Connecticut,USA,2020-04-07 01:00:00,6906,206,0
250,Colorado,USA,2020-04-07 01:00:00,5183,150,0
251,Indiana,USA,2020-04-07 01:00:00,4956,143,0
252,Ohio,USA,2020-04-07 01:00:00,4453,142,0
253,Maryland,USA,2020-04-07 01:00:00,4045,91,0
254,Tennessee,USA,2020-04-07 01:00:00,3802,65,0
255,North Carolina,USA,2020-04-07 01:00:00,3054,45,0
256,Virginia,USA,2020-04-07 01:00:00,2878,66,0
257,Missouri,USA,2020-04-07 01:00:00,2736,62,0
258,Wisconsin,USA,2020-04-07 01:00:00,2511,85,0
259,Arizona,USA,2020-04-07 01:00:00,2456,65,0
260,South Carolina,USA,2020-04-07 01:00:00,2232,48,0
261,Alabama,USA,2020-04-07 01:00:00,2006,53,0
262,Nevada,USA,2020-04-07 01:00:00,1953,46,0
263,Mississippi,USA,2020-04-07 01:00:00,1738,51,0
264,Utah,USA,2020-04-07 01:00:00,1680,13,0
265,Oklahoma,USA,2020-04-07 01:00:00,1329,51,0
266,Idaho,USA,2020-04-07 01:00:00,1170,13,0
267,Oregon,USA,2020-04-07 01:00:00,1132,29,0
268,District of Columbia,USA,2020-04-07 01:00:00,1097,24,0
269,Rhode Island,USA,2020-04-07 01:00:00,1082,27,0
270,Kentucky,USA,2020-04-07 01:00:00,1008,60,0
271,Minnesota,USA,2020-04-07 01:00:00,986,30,0
272,Iowa,USA,2020-04-07 01:00:00,946,25,0
273,Arkansas,USA,2020-04-07 01:00:00,927,16,0
274,Kansas,USA,2020-04-07 01:00:00,849,25,0
275,Delaware,USA,2020-04-07 01:00:00,783,15,0
276,New Hampshire,USA,2020-04-07 01:00:00,715,9,0
277,New Mexico,USA,2020-04-07 01:00:00,686,12,0
278,Vermont,USA,2020-04-07 01:00:00,543,23,0
279,Puerto Rico,USA,2020-04-07 01:00:00,513,21,0
280,Maine,USA,2020-04-07 01:00:00,499,10,0
281,Nebraska,USA,2020-04-07 01:00:00,417,9,0
282,Hawaii,USA,2020-04-07 01:00:00,387,5,0
283,Navajo Nation,USA,2020-04-07 01:00:00,354,14,0
284,West Virginia,USA,2020-04-07 01:00:00,345,4,0
285,Montana,USA,2020-04-07 01:00:00,319,6,0
286,South Dakota,USA,2020-04-07 01:00:00,288,4,0
287,North Dakota,USA,2020-04-07 01:00:00,225,3,0
288,Wyoming,USA,2020-04-07 01:00:00,212,0,0
289,Alaska,USA,2020-04-07 01:00:00,191,6,0
290,Guam,USA,2020-04-07 01:00:00,113,4,0
291,Grand Princess,USA,2020-04-07 01:00:00,103,3,0
292,Diamond Princess,USA,2020-04-07 01:00:00,49,0,0
293,United States Virgin Islands,USA,2020-04-07 01:00:00,43,1,0
294,Northern Mariana Islands,USA,2020-04-07 01:00:00,8,1,0
295,Wuhan Evacuee,USA,2020-04-07 01:00:00,4,0,0

In [ ]:
# make df as needed for the bar chart race